### ISSUE TITLE
Iteration interface for DifferentialEquations.ODESolution

### ISSUE THREAD

**Issue by AlexanderKoshkarov** [JuliaDiffEq/DifferentialEquations.jl#108]
It would be nice to have the iteration interface for DifferentialEquations.ODESolution type.
```
>typeof(sol) == DifferentialEquations.ODESolution
true
>sol[1]; # no error
> [somefun(s) for s in sol];
ERROR: MethodError: no method matching start(::DifferentialEquations.ODESolution)
```

**Comment by ChrisRackauckas** [comment]
A quick hack is just to use `sol.timeseries`:

```julia
[somefun(s) for s in sol.timeseries]
```

But an interator interface already partially exists because of the Plots.jl animation changes: https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/105

You can probably just add this:

```julia
function start(sol::DESolution)
  #sol.tslocation = state
  1
end

function next(sol::DESolution,state)
  state += 1
  #sol.tslocation = state
  (sol,state)
end

function done(sol::DESolution,state)
  state >= length(sol)
end

function eltype(sol::DESolution) 
  if typeof(sol[1]) <: AbstractArray
    return typeof(sol[1][1])
  else
    return typeof(sol[1])
  end
end
```

The `tslocation` parts will be used in the animations, but for now the fields only exist for `FEMSolution` so it's commented out.

Note that there is a big push to get this common interface mapped directly onto all of the packages (instead of via a wrapper in OrdinaryDiffEq.jl)

https://github.com/JuliaDiffEq/Roadmap/issues/5

So if you're on master, in a few days there will be some API changes (I'll update the docs and put out a blog post summarizing the whole thing).

[BTW, you can set an `internalnorm` now if you're on DifferentialEquations.jl master with OrdinaryDiffEq.jl master. `internalnorm(u)` is the norm for the error and defaults to:

```julia
@inline function ODE_DEFAULT_NORM(u)
  for i in eachindex(u)
    u[i] = u[i]*u[i]
  end
  sqrt( sum(u) / length(u))
end
```

This is the Hairer length-adjusted L2 norm, but you can pass any one parameter function to be the norm that you like.]

**Comment by ChrisRackauckas** [comment]
As discussed in chat, you can always do:

```julia
[@show (t,y) for (t,y) in tuple.(sol.t,sol.u)]
```

To get the tuples you want. On master there's a helper function `tuples(sol) = tuple.(sol.t,sol.u)` since this is probably the most common case:

```julia
[@show (t,y) for (t,y) in tuples(sol)]
```
