### ISSUE TITLE
ODE tutorial examples fail

### ISSUE THREAD

**Issue by portig** [JuliaDiffEq/DifferentialEquations.jl#109]
At least the first two examples in the ODE tutorial no longer work in Julia 0.5 and 0.6. The error occurs with the call to ODEProblem:

julia> prob = ODEProblem(f,u0,tspan)

ERROR: MethodError: no method matching DifferentialEquations.ODEProblem{uType<:Union{AbstractArray,Number},uEltype<:Number}(::#f, ::Array{Float64,2}, ::Tuple{Float64,Float64})
Closest candidates are:
  DifferentialEquations.ODEProblem{uType<:Union{AbstractArray,Number},uEltype<:Number}(::Function, ::Any; analytic) at /Users/Software/.julia/v0.5/DifferentialEquations/src/general/problems.jl:397
  DifferentialEquations.ODEProblem{uType<:Union{AbstractArray,Number},uEltype<:Number}{T}(::Any) at sysimg.jl:53

Evidently this is because typeof(f) now returns "#f" and not "Function". . .

**Comment by ChrisRackauckas** [comment]
Yes, this is known. This is because there was a huge change to DifferentialEquations.jl and its interface, the documentation has been updated to this new interface, but it won't actually be "live" in Julia from `Pkg.add` until until the tags go through. 

To track the tags, you can see this: https://github.com/JuliaLang/METADATA.jl/pull/7006

And there will be a similar one for DifferentialEquations.jl. When those get merged into METADATA, then the user install will put you on the correct (the new) interface. I hope that happens today, but it's out of my control.

Sorry for the inconvenience!

**Comment by ChrisRackauckas** [comment]
>Evidently this is because typeof(f) now returns "#f" and not "Function". . .

Note that's not actually a problem because the function types `#f` subtype `Function`, and so it would still put the function into the type, but just not be strictly typed. The real issue here is that `tspan` only goes into the `ODEProblem` with the newest changes (look at the difference in the function signature for what it suggests). That's the breaking change, and I'd suggest just waiting.

**Comment by ChrisRackauckas** [comment]
This should be fixed with `Pkg.update()`. Please re-open if you have any other issues.
