### ISSUE TITLE
Documentation for plot(sol)

### ISSUE THREAD

**Issue by alavendelm** [JuliaDiffEq/DifferentialEquations.jl#112]
plot(sol) is opaque and I can't find in the docs a description of what is actually being called here. 

e.g. how to plot an ODESolution in parts: plot(sot.t, sol.u) seems intuitive but doesn't work.

May be related to #111, in terms of additional plotting functionality in the future?

**Comment by ChrisRackauckas** [comment]
>plot(sol) is opaque and I can't find in the docs a description of what is actually being called here.

https://juliadiffeq.github.io/DiffEqDocs.jl/latest/basics/plot.html

It's calling a plot recipe which is essentially `plot(sot.t, sol[:,i])` for each component `i`. 

>e.g. how to plot an ODESolution in parts: plot(sot.t, sol.u) seems intuitive but doesn't work.

Yes, that is because the solution timeseries `u` is a `Vector{Vector{T}}`, and not a vector or matrix of numbers (this is because it allows increased efficiency and more general (changing size) problems). If you want to plot a component, you need to turn this into a vector of numbers. The easiest way is likely `sol[:.i]` which will give the timeseries for the `i`th component.

 >May be related to #111, in terms of additional plotting functionality in the future?

Yes, it's getting reworked in #111. If you have any ideas, please post them over in that thread.

**Comment by alavendelm** [comment]
Ok thanks.
