### ISSUE TITLE
Implementing backward stepping for Final Value Problems, FVP, in ODE integration

### ISSUE THREAD

**Issue by JuanCarlosCuchi** [JuliaDiffEq/DifferentialEquations.jl#114]
In other scripting Languages, Mathematica or matlab for instance, it is possible to solve FVP simply by inverting the interval of integration without modfying the differential equations by hand. That is, changing tspan= (t1,t2) to tspan=(t2,t1). Even though this is not an essential feature I think it should be useful to implement it in the DifferentialEquations package.

**Comment by ChrisRackauckas** [comment]
Yes, it would be useful. There are a few places in the code which would have to be changed to keep track of the direction, but it's not too difficult to support. This is definitely on the list.

**Comment by ChrisRackauckas** [comment]
Note that ODE.jl can do this (and has DiffEq interface bindings).

**Comment by JuanCarlosCuchi** [comment]
You are right, I had no idea. When I began to investigate how to solve differential equations with Julia, past summer, I tested the ODE package and looked at the examples, but not the docs. In any case I decided not to use it for some reasons:

- As you pointed out, it's possible to invert the interval of integration by hand.

- The extraction and ordering of data from the answer, to examine and plot them, is rather cryptic.  I finally used    `coord = hcat(coord...).';`. Instead, in DiffEq this is really easy and clear. May be, using ODE from DifferentialEquations (DiffEq for short) with the interface bindings this objection is cleared

- We are working in a problem of quantum evolution on the surface of the Bloch Sphere. The question is that we need that during the evolution the trajectory remains on this surface. So the integration algorithm must be unitary. We solved a partial approach to the problem, solving the evolution by pieces, using Mathematica with a implicit Gauss-Legendre method of order 4 (GL4). (The paper is now in a journal limbo) But if we try to solve the full problem together,  even in the simpler cases, Mathematica is too slow. The ODE package does not have any symplectic unitary method but DiffEq has the GL4 and GL6 Butcher Tableaus.  I know that there is a new package for symplectic algorithms and probably there will be interface bindings from DiffEq, but, right now, with GL4 or GL6 is enough.

- Also When using DiffEq an interpolator of the solution is created and that's  useful for our problem. I'm not going to explain it now because this is not the place; may be next term, without teaching, I'll ask you, in Gitter .

- And finally, unlike for DiffEq, examples and docs for ODE are nearly inexistent. The docs and examples you provide make your package even better. 

Any case, my suggestion is not an essential one.  DiffEq is a wonderful package and it should be interesting, as someone told you in the Gitter chanel, a way of citing it in the papers. Cites are a important in this business. May be a paper to the arxiv?, you ever can modify it when necessary or publish it later. Well, this comment is becoming too long, I apologize for my English and I wish you Happy New Year.

**Comment by ChrisRackauckas** [comment]
This has been implemented in OrdinaryDiffEq.jl with https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/commit/40752c76051d2395793277bdd06c8cb63e28e37e

and in Sundials with https://github.com/JuliaDiffEq/Sundials.jl/pull/107 . Future tags will make this functionality readily available.

As for your other points, thanks for the feedback and the kind words!

- Indeed, working with vectors of vectors is difficult. The DiffEq bindings on ODE.jl do make it act like DiffEq, so there should be a degree of uniformity in the interface. 

- Included in a DiffEqBase commit is that the plot axis will automatically flip though when integrating backwards. That's another usability win. Once again, that will be released whenever tags start going through.

- I will be making bindings for GeometricIntegrators.jl so that way some geometric integrators are available. However, those are all fixed timestep, so I hope to work on some in the future, but other things are on the docket first.

- Come discuss whenever. I'm always in the room.

- I am making more and more docs for all of the packages in the ecosystem daily. I hope to get around to ODE soon.

- I submitted a paper back in September, but it's lost in publishing limbo (they said it's still being reviewed? Maybe this software is just much larger than what they are used to!). I'll be making a citation section for the docs pretty soon.

Since has been implemented, I'm closing this. However, you will need to wait for tags which include the mentioned commits before it's truly released.
