### ISSUE TITLE
define size for Solution types so end works

### ISSUE THREAD

**Issue by ggggggggg** [JuliaDiffEq/DifferentialEquations.jl#123]
Unless there is some reason `sol[1:end,1]` can't work.

```
julia> using DifferentialEquations

julia> α=1
1

julia> u0=1/2
0.5

julia> f(t,u) = α*u
f (generic function with 1 method)

julia> tspan = (0.0,1.0)

(0.0,1.0)

julia> prob = ODEProblem(f,u0,tspan)
DiffEqBase.ODEProblem{Float64,Float64,false,#f}(f,0.5,(0.0,1.0))

julia> sol = solve(prob)
DiffEqBase.ODESolution{Array{Float64,1},Array{Float64,1},Array{Array{Float64,1},1},DiffEqBase.ODEProblem{Float64,Float64,false,#f},OrdinaryDiffEq.Tsit5}([0.5,0.552608,0.708178,0.990077,1.35914],[0.0,0.10004,0.348088,0.683175,1.0],Array{Float64,1}[[Inf],[0.5,0.508053,0.516627,0.547151,0.551587,0.552699,0.552608],[0.552608,0.574676,0.599267,0.691649,0.70619,0.709839,0.708178],[0.708178,0.746384,0.790071,0.960041,0.988208,0.995271,0.990077],[0.990077,1.04058,1.09802,1.31982,1.35618,1.3653,1.35914]],DiffEqBase.ODEProblem{Float64,Float64,false,#f}(f,0.5,(0.0,1.0)),OrdinaryDiffEq.Tsit5
  order: 5
  adaptiveorder: 4,OrdinaryDiffEq.#130,true,0)

julia> sol[:,1]
5-element Array{Float64,1}:
 0.5     
 0.552608
 0.708178
 0.990077
 1.35914 

julia> sol[1:end,1]
ERROR: MethodError: no method matching size(::DiffEqBase.ODESolution{Array{Float64,1},Array{Float64,1},Array{Array{Float64,1},1},DiffEqBase.ODEProblem{Float64,Float64,false,#f},OrdinaryDiffEq.Tsit5}, ::Int64)
Closest candidates are:
  size{N}(::Any, ::Integer, ::Integer, ::Integer...) at abstractarray.jl:48
  size(::BitArray{1}, ::Any) at bitarray.jl:43
  size(::Char, ::Any) at char.jl:14
  ...
```

**Comment by ggggggggg** [comment]
Actually indexing with a range doesn't work at all
```
julia> sol[1:2,1]
ERROR: MethodError: no method matching getindex(::DiffEqBase.ODESolution{Array{Float64,1},Array{Float64,1},Array{Array{Float64,1},1},DiffEqBase.ODEProblem{Float64,Float64,false,#f},OrdinaryDiffEq.Tsit5}, ::UnitRange{Int64}, ::Int64)
```
I would expect the output to be identical to 
```
julia> sol[:,1][1:2]
2-element Array{Float64,1}:
 0.5     
 0.552608
```

**Comment by ChrisRackauckas** [comment]
Note that `length(sol)` is already defined, so `sol[2:end]` should work, but to make `sol[1:end,1]` work you need `size`. The problem with that is we cannot guarantee that it has a "rectangular size". You can use events/callbacks to continually change the size of the ODE system ([here's the example from the manual](https://juliadiffeq.github.io/DiffEqDocs.jl/latest/features/callback_functions.html#Example-2:-Growing-Cell-Population-1)), and `sol` will represent that correctly, but the "size" in the 2nd dimension doesn't make sense because it's changing according to where you are in the first dimension. So I am not sure we can ever get `sol[1:end,1]` to work, though `sol[1:length(sol),1]` is something we could get working. But...

>Actually indexing with a range doesn't work at all

Sounds like we're missing some dispatches here:

https://github.com/JuliaDiffEq/DiffEqBase.jl/blob/master/src/solutions/solution_interface.jl#L3

**Comment by ChrisRackauckas** [comment]
Added a dispatch:

```
julia> sol[1:3,1]
3-element Array{Float64,1}:
 0.260125
 0.276545
 0.294002

julia> sol[1:length(sol),1]
17-element Array{Float64,1}:
 0.260125
 0.276545
 0.294002
 0.312561
 0.332292
 0.353268
 0.375568
 0.399275
 0.42448
 0.451275
 0.479762
 0.510047
 0.542243
 0.576472
 0.612862
 0.651549
 0.692678
```

That's on DiffEqBase master. There will be a full ecosystem tag going through soon which will include this.

**Comment by ChrisRackauckas** [comment]
[I posted the question on whether this is possible to Discourse](https://discourse.julialang.org/t/using-end-when-size-is-not-definable/1138/1). If there's no good solution, then I'll close this, having fixed all but the `end` issue.

**Comment by ChrisRackauckas** [comment]
Solved via [@nalimilan's suggestion](https://discourse.julialang.org/t/using-end-when-size-is-not-definable/1138/2). 

https://github.com/JuliaDiffEq/DiffEqBase.jl/commit/a750a9048d2a4bf514667517e3ad65b4222c2a65
