### ISSUE TITLE
rename the `save_timeseries` to a more intuitive name and make it `=false` when `saveat` is provided

### ISSUE THREAD

**Issue by Datseris** [JuliaDiffEq/DifferentialEquations.jl#133]
The `save_timeseries` keyword for `solve()` can be non-intuitive, specifically when used in parallel with `saveat`.

Firstly, I suggest that if a `saveat` is provided, the keyword `save_timeseries` (which a name-change is suggested here) should default to `false` instead. The reasoning is very simple:
With `saveat` I specify to the solver exactly at which points I want my solution. Why would I possibly want the timeseries at the points the integrator stopped? I have already specified the points I want using the vector passed to `saveat`.

Secondly, maybe a better keyword would be one that *stresses* that in fact what is going on is that the output is saved at every point the integrator stops (*in addition to the points provided by the user, if they are provided*).

Therefore I can suggest the following (without any claim for perfection!):

1. `everystep`
2. `save_everystep`
3. `savestops`
4. `save_stops`
5. `sis` (from save-internal-steps)
6. `ses` (from save-every-step)

I lastly add that even though the last 2 options are very short, they are worth considering nevertheless because they reduce visual noise and they feel like they are in the same line as julia's core style.

**Comment by ChrisRackauckas** [comment]
I like `save_everystep` since I think that, if you have to look at documentation to know what an argument means, then is not named correctly.

**Comment by Datseris** [comment]
When the changes are merged I am going to make a PR at the docs that is clean, concise and has all the latest keywords and interactions. Just let me know when the changes will happen.

`save_everystep` is fine. I tend to like a bit more some option like `save_everystop` or `save_stops` but as long as the documentation is clear and concise all of these options are fine.

**Comment by ChrisRackauckas** [comment]
>save_everystep is fine. I tend to like a bit more some option like save_everystop or save_stops but as long as the documentation is clear and concise all of these options are fine.

I think that would get confused with something like `save_everytstop` which would only save at `tstop` values (which I don't think makes sense to implement given the `saveat` behavior, but the wordage difference between `stops` and `tstops` is just so small I can see it causing issues)

**Comment by Datseris** [comment]
Fair enough.

**Comment by gabrielgellner** [comment]
Does it not make sense to save the `saveat` timepoints in a separate field? That way the issue of polluting the meshpoints of the integrator doesn't happen? I guess the only issue is how to deal with the interface for accessing the points from the sol output.

**Comment by ChrisRackauckas** [comment]
>Does it not make sense to save the saveat timepoints in a separate field? That way the issue of polluting the meshpoints of the integrator doesn't happen? I guess the only issue is how to deal with the interface for accessing the points from the sol output.

This would screw with the array interface. Making it able to access two fields and be semi-efficient (it doesn't need to be perfectly efficient, but at least try) would be impossible I think. But it would fix the issue of having to track `notsaveat_idxs` which is currently done for the interpolations. 

But this could be the solution: save a `VectorOfArray` to a field, like `sol.saveat`, and keep it separate from `sol.u` and its array interface.

**Comment by gabrielgellner** [comment]
That sound really promising. Then the user would just need to access the `sol.saveat[:, i, j, ..]` etc yes?

**Comment by ChrisRackauckas** [comment]
>Then the user would just need to access the sol.saveat[:, i, j, ..] etc yes?

Yes.

**Comment by Datseris** [comment]
hey, glad to see that people are commenting on this.
Just one worry from my side? Would it be true to say that if one adds more fields on the `sol` object, it would make it's handling slower? I am not very familiar of the inner workings of the `sol` object but I would guess the more additional data one has to carry around the slower it would get?

**Comment by ChrisRackauckas** [comment]
>Would it be true to say that if one adds more fields on the sol object, it would make it's handling slower? I am not very familiar of the inner workings of the sol object but I would guess the more additional data one has to carry around the slower it would get?

No, I tested this a bit once, and from what I could tell there's really no measurable cost to adding more fields. I believe that essentially what happens is there would be one more pointer in the type. But if the field access is known at compile-time (which is essentially always), then it's just dereferencing a different pointer.

So a solution which does `saveat` to a different field would be fine performance-wise. It would actually speedup the case where you have `saveat` and interpolations, because then the interpolation array would be contiguous. But this would be really minor: assume the speed is essentially the same.

**Comment by Datseris** [comment]
Oh really? Well this is something good to know in general I guess!!!

**Comment by ChrisRackauckas** [comment]
>Oh really? Well this is something good to know in general I guess!!!

Yes. One caveat here: this is mutable types. Mutable types add a pointer for each field, which is not really much at all, so there's really no performance gain/loss (only the gain/loss of needing to build the object for the extra field, but if it's just putting arrays in a different spot, then it's no difference). Immutable types are value-types, so they have their values directly instead of pointers. These will grow in size depending on the values put in there. But even that doesn't matter that much, because the value for an array is its reference (pointer), so you'd only end up loosing performance if you had an immutable type with tons of large bit numbers or something like that.

**Comment by ChrisRackauckas** [comment]
Implemented

**Comment by ChrisRackauckas** [comment]
Note that I put it in `u`. The reason for this is because now, by default, `saveat` turns off `save_everystep`. This means that in the most standard case where `saveat` is used, there's no issue with putting it in `u`. It also means that things which only have linear interpolations or piecewise constant interpolations (stochastic equations or discrete equations) still work even with only `saveat`. Also, it means the array interface works. 

If it was put to another array, the array interface wouldn't work, and even if you could interpolate with `saveat` and no `u` (linear and piecewise constant), it wouldn't without a lot of extra hassle and performance issues (it would need a whole mechanism for deciding which field to use, which could mean another time array too, and comparing times before every interpolation).

So the current setup here is better. It will only mix them if you explicitly do `saveat` and give it `save_everystep=true`, which might be more rare case than we're giving credit. Even then, I would question that usage since you likely should be interpolating afterwards if you want both... but I have this all in place so you can be you and do whatever crazy analysis you want.

**Comment by gabrielgellner** [comment]
Yeah it makes sense that saveat basically turns off all the advanced features. If we agree to adding an array interface to the interpolation output, I really only see myself using saveat when I want a static set of points for speed.

**Comment by ChrisRackauckas** [comment]
>I really only see myself using saveat when I want a static set of points for speed.

Yeah, I think that should be the point of it: when you want the speed (or memory saving for a large PDE, the speed difference honestly isn't very much unless you have large arrays) of not saving anything other than a few timepoints. Other than that, everything else can use defaults.
