### ISSUE TITLE
Linking with Stan project

### ISSUE THREAD

**Issue by hwxie** [JuliaDiffEq/DifferentialEquations.jl#135]
Hi Chris,
Wally here, just leaving a message per our discussion earlier to get the conversation started on the project to link DifferentialEquations.jl with Stan. What should I be reading up on as a primer and what is an exercise I could do to get started so I can come to grips with what this project would entail? 

Thanks!

**Comment by ChrisRackauckas** [comment]
Hey,
  Thanks for being interested in GSoC. The outline for the project is listed here:

http://julialang.org/soc/projects/diffeq.html

  The idea is to build this functionality directly off of the `ParameterizedFunction`. ParameterizedFunctions.jl is a generic way which functions in parameters can be describe for usage with DifferentialEquations.jl. It's first described in the tutorial here:

  http://docs.juliadiffeq.org/latest/tutorials/ode_example.html#Defining-Systems-of-Equations-Using-ParameterizedFunctions.jl-1

  However, there's tons of stuff in the `ParameterizedFunction`. The type that the macro generates is described here:

  https://github.com/JuliaDiffEq/ParameterizedFunctions.jl/blob/master/src/maketype.jl#L24

Basically, it already calculates the symbolic Jacobians, inverts Jacobians if possible, etc. to make other calculations faster. But for our purposes, it know how it was defined. Example:

```julia
f = @ode_def LotkaVolterra begin
  dx = a*x - b*x*y
  dy = -c*y + d*x*y
end a=>1.5 b=>1 c=3 d=1
println(f.origex)
f = @ode_def LotkaVolterra begin
  dx = a*x - b*x*y
  dy = -c*y + d*x*y
end a=>1.5 b=>1 c=3 d=1
println(f.origex)
```

which prints:

```
begin  # console, line 2:
    dx = a * x - b * x * y # console, line 3:
    dy = -c * y + d * x * y
end
```

And it also has already parsed this to know the user's variable names, the parameter names, their values, etc.

So this is something that DifferentialEquations.jl already has, it's in many user codes, is super easy to use, and it has the full information to do whatever you want. So, there should be a way to, for whatever you want to do with Stan, directly use this to write Stan models automatically so that way the same code you write for solving differential equations will automatically be Stan-compatible.

http://mc-stan.org/documentation/

(in their manual, they use a Dormand-Prince 4/5 algorithm to solve a noisy problem, and pretend that actually works... there's no convergence proof for that and it may not actually converge, and if it does, it's bounded to have order less than or equal to 1/2 by a proof in Kloden, Platen, Schwartz... and I'll just pretend like I didn't see this in their docs)

Now I don't think that you can actually make Stan use the DifferentialEquations.jl solvers, so it's limited to what they have implemented. It's sad, but it'll do for now. You should be able to directly write a Stan model from a ParameterizedFunction. Then you should be able to use Distributions.jl to be able to define the distributions on the parameters, and that should make a full Stan model for parameter estimation, which should just run. Yay, now you can run parameter estimation in Stan with almost no code modification.

If you want to go a step further, then this could turn into a deeper research project with connecting the differential equation solvers directly with an MCMC backend. I would recommend doing the Stan part first because that would be needed at least for validation, but the cool thing here is that a setup with an MCMC backend would make it have more efficient ODE solvers, and allow parameter estimation on SDEs, DDEs, DAEs, PDEs, SPDEs, etc. so it would be a really nice outcome. For this, you could look into using Klara.jl or Mamba.jl which are really nice MCMC packages,and build the likelihood from a ParameterizedFunction and a diffeq solver. (It might be worth opening up issues on the Stan, Klara, and Mamba pages to get more information from their authors as well as to how possible and how hard it is to link the solvers.)

Depending on your Julia knowledge, the Stan part could be a quick exercise, or it could be the whole summer. Either way, it's a nice outcome itself, since I think many people who aren't Bayesian statisticians don't know and will never learn how to directly write Stan models, but `ParameterizedFunctions` are very natural to someone who solves diffeqs. (Actually, it's also used in [DiffEqOnline](http://app.juliadiffeq.org/) so it would make it extremely easy to offer a web interface for parameter estimation using Stan, which would definitely raise a lot of eyebrows).

**Comment by hwxie** [comment]
Thanks Chris for your detailed response. I think the Stan part will
probably take me the whole summer.

So from what I read here, it appears that this is the desired process:

1) Create model in Julia ```ParametrizedFunction``` code.

2) DiffEqParamEstim.jl translates model code to Stan model code and calls
Stan.

3) Stan (using its rk45 or cvode solver -- the two solvers it has access
to) generates posterior distribution of parameters.

4) DiffEqParaEstim.jl extracts information from posterior distribution and
returns parameter information.

Is this correct?

**Comment by ChrisRackauckas** [comment]
Yes.

**Comment by ChrisRackauckas** [comment]
Closing as a dup of https://github.com/JuliaDiffEq/DiffEqParamEstim.jl/issues/3
