### ISSUE TITLE
Bad interpolation with array arguments for backward integration

### ISSUE THREAD

**Issue by fedxa** [JuliaDiffEq/DifferentialEquations.jl#142]
If the solution of the ODE was made in negative time direction, then the resulting interpolator works only if called with sngle numbers, if it is called with array as the argument it returns wrong result.  In the code below the two final lines should produce the same result, while they do not

    probfail = ODEProblem(function (t,x) x end, 1., (1.0,0.0))
    solfail = solve(probfail, Euler(), dt=-0.1)
    [solfail(0), solfail(1)]
    solfail([0,1])

**Comment by ChrisRackauckas** [comment]
Thanks! Really nice bug report. Fixed by https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/commit/8259e31d15653cc492e6b7148205fb77d2b945a4 and https://github.com/JuliaDiffEq/StochasticDiffEq.jl/commit/485ebdb31a34b1bcbd0da11ad47a8dca63642bb1 . For now it's on master for those, but I am considering doing a patch release soon for a few things.

**Comment by fedxa** [comment]
Lightning fast! Thank you 👍
