### ISSUE TITLE
Differential Equations not running correctly on Julia 0.6.0

### ISSUE THREAD

**Issue by jagomezr** [JuliaDiffEq/DifferentialEquations.jl#143]
I'm trying to run the following piece of code:

using DifferentialEquations
α=1
u0=1/2
f(t,u) = α*u
tspan = (0.0,1.0)
prob = ODEProblem(f,u0,tspan)
sol = solve(prob)

and I get the following error:

LoadError: LoadError: LoadError: invalid subtyping in definition of JumpProblem
while loading /home/jagomezr/.julia/v0.6/DiffEqJump/src/problem.jl, in expression starting on line 1
while loading /home/jagomezr/.julia/v0.6/DiffEqJump/src/DiffEqJump.jl, in expression starting on line 19
while loading /home/jagomezr/.julia/v0.6/DifferentialEquations/src/DifferentialEquations.jl, in expression starting on line 23

Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:539
 [2] include(::String) at ./sysimg.jl:14
 [3] include_from_node1(::String) at ./loading.jl:539
 [4] eval(::Module, ::Any) at ./boot.jl:235
 [5] require(::Symbol) at ./loading.jl:453
 [6] include_from_node1(::String) at ./loading.jl:539
 [7] eval(::Module, ::Any) at ./boot.jl:235
 [8] require(::Symbol) at ./loading.jl:453

**Comment by ChrisRackauckas** [comment]
Yes. It is not ready for v0.6 yet. Might as well make this the issue for keeping track of the changes.

- [ ] DiffEqJump is fixed on master, needs a tag.
- [ ] DiffEqBase is fixed on master, needs a tag.
- [ ] ParameterizedFunctions is fixed on master (no more evals!), needs a tag.
- [ ] OrdinaryDiffEq is mostly fixed on master, but ran into a problem with Base. https://github.com/JuliaLang/julia/issues/20998 . I don't think that we can be compatible with v0.6 until this bug in Julia is fixed. Other than that, OrdinaryDiffEq seems to work.
- [ ] StochasticDiffEq seems to have the same issue as OrdinaryDiffEq, and will be fixed by the same Base fix.
- [ ] Sundials, MultiScaleArray, DelayDiffEq, and ODE need the updates for the abstract type syntax change, and updated `Compat` requirements.
- [ ] Sundials needs its type-aliases to be renamed (depwarn)
- [ ] MultiScaleArrays needs its broadcast overloads changed.
- [ ] SymEngine is fixed on master, needs a tag.

Please let me know if there's anything I am missing. A lot of these PRs are simple syntax changes, so help would be highly appreciated!

**Comment by ChrisRackauckas** [comment]
Updates: a few tags have gone in. DiffEq solvers seem to work on master. Still a bunch of depwarns but the next round of tags will be working. Most of the depwarns are from NLsolve and not DiffEq packages though.

**Comment by ChrisRackauckas** [comment]
DiffEq should work on v0.6 using release versions now. However, you'll get lots of depwarns. Those will get cleaned up by the time v0.6 is out of alpha. Please report any problems you run into. Also, please submit some PRs that fix depwarns if you can!

**Comment by ChrisRackauckas** [comment]
Closing, make separate issues/PRs for depwarns
