### ISSUE TITLE
@compat not defined

### ISSUE THREAD

**Issue by huckl3b3rry87** [JuliaDiffEq/DifferentialEquations.jl#144]
I am getting this error on a Windows machine

![capture](https://cloud.githubusercontent.com/assets/8204378/23967636/0b6d8fec-0996-11e7-9a1b-58efffbbe01e.PNG)

**Comment by ChrisRackauckas** [comment]
https://discourse.julialang.org/t/nested-macros-bypass-package-dependencies/2683/4

The tl;dr is: the fix is in this METADATA PR:

https://github.com/JuliaLang/METADATA.jl/pull/8343

Should be able to Pkg.update pretty soon.

**Comment by ChrisRackauckas** [comment]
Dup of https://github.com/JuliaDiffEq/StochasticDiffEq.jl/issues/16

**Comment by huckl3b3rry87** [comment]
@ChrisRackauckas sorry did not see that one.

Thanks!

**Comment by ChrisRackauckas** [comment]
Update: we are going with the route of just doing a long-term fix to Parameters.jl. I already submitted that PR: https://github.com/mauro3/Parameters.jl/pull/28 . That should get through and we can tag probably by tomorrow.

In the meantime, you can get things working again by doing:

```julia
Pkg.pin("Parameters",v"0.6.0")
```

You'll have to remember in the future to `Pkg.free("Parameters")` so that way it will update properly though!

**Comment by ChrisRackauckas** [comment]
Should be fixed now.
