### ISSUE TITLE
Refactoring the Solution Interface

### ISSUE THREAD

**Issue by gabrielgellner** [JuliaDiffEq/DifferentialEquations.jl#152]
As a recap we have the current solution interface giving the extremely nice behavior with:

```julia
sol.t # solution times
sol.t[i] # i-th time value
sol[i] # gives the i-th array of state variables (sol.u[i])
sol[i, j, ...] # gives sol.u[i][j, ...]
sol(ts) # gives back the solution interpolated to the ts
```
This is great, but some of the unfinished edges are:

1. `sol(ts)`, doesn't return a solution that has the same nice behavior, so you can't do
   what you might expect like:
   ```julia
   isol = sol(ts) # ts::AbstractVector
   isol[:, 1] # get the interpolated values for variable 1
   ```
   It might even make sense to have it so it has the above solution interface so you could
   further do:
   ```julia
   isol.t # the grid of interpolation times
   isol.t[i] # the i-th interpolation time
   ```
2. Not all indexing is currently supported for the `sol[i, j, ...]` behavior. Really only
   the common whole forms like `sol[I::Union{Colon, Int}, i::Union{Int, AbstractArray{Int}}]`
   will return a convenient `Array{T, N}` like interface, otherwise a plain vector of arrays
   is returned, which makes further analysis feel awkward.

Now moving forward it would be nice to be more full featured with this. I have spoken
extensively with Chris about how we might fix up some of this. And he seems positive that
such extensions would be welcome, we just need to decide as a community about some of the
semantic issues this brings up.

The main issue is how to think about what a vector of array's means for index order. Given
the standard Julia vector of arrays (of all the same size):

```julia
recs = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
```

How do we think about index order? It is natural to have the mapping `recs[i][j] -> recs[i, j]`,
which gives the C like behavior of meaning the subarrays (vectors) are being stacked by rows.
If instead we think of the common way you might convert this to a matrix in Julia you would
have:

```julia
va = hcat(recs...)
```

Then we have the subarrays stacked by columns. Obviously we could transpose the above to
make it have the `recs[i][j] -> recs[i, j]` semantics. But generalizing this to `Array{T, N}`,
subarrays is less clear. To do so we would need to be transposing each dimensions subarray
to keep the behavior consistent.

Given this I feel the best way moving forward is to have the solution type instead stack by
columns, then we have the n-dimensional case work naturally from the Julia machinery. In
doing so we would just need to start visualizing our DiffEq output as having the time series
for a variable along the rows (`sol[1, :]` instead of `sol[:, 1]`). Given this behavior
it is then trivial to have `sol[1:2, 1:2]` etc. return a `Array{T, N}` with the usual Julia
semantics, and we do not need to show the end user the fact that the underlying data structure
is actually a vector of arrays.

At https://github.com/gabrielgellner/VectorOfArrayTools.jl we have the basic behavior implemented (really this comes from Matt Bauman and Chris Rackauckas, I just bundled it up, all silly mistakes are my own) in the type called `VectorOfArray`.

Something I am also trying to add is a way to turn off the array indexing when the solver,
or user adds a subarray with a different shape, turning the `VectorOfArray` ragged. If this
occurs then the "fancy" indexing is turned off, and only the underlying `sol.u[i][i, j,...]`
can be used.

**Comment by ChrisRackauckas** [comment]
Thanks for this write-up! I'll be calling for community input here as in the end, I want the API to be what the community finds intuitive. I think it's important to note that NONE of the actual DiffEq ecosystem actually uses this internally (except in tests of the interface itself!), so in some sense this is actually really trivial to change, but it will be a nontrivial and breaking API change to users so it should still be done with caution.

The interpolation will only return values. This is because it is used internally by many different things where it needs to be as lightweight as possible. Making it build a solution type each time will slow down things like the DelayDiffEq solvers, and will slow down uses of `saveat` (unless it's not applied to the integrator interface's interpolation, which would be very weird since right now they just act the same). The solution type that would be returned wouldn't be able to interpolate itself, or have large amounts of the other functionality. In the end, it would just be a VectorOfArray with an extra field with `t` anyways, and I don't know how useful it is when you gut it to there, but it will still be a lot more expensive because it's not just using the array buffer type (which in Julia seems to be slightly faster to create).

But I think that there are many good points made here for "arrays as columns". Ultimately, I'll let users decide if they want this change. 

**Please feel free to comment!**

**Comment by gabrielgellner** [comment]
As Chris makes clear, really what I am advocating for the interpolation solution type, is really just a `VectorOfArray` with a `t` field, not the extra machinery beyond that, something like a `DEInterpArray` or some similar type name.

For the interp not returning anything but values, could we not just overload the solution call for when it gets a `AbstractArray` input of time points? This way there is no overhead for when it is being used internally, but gives the interpolated solution a nice API for the end user (this should just be a one line method definition on the solution so that it wraps the interp call in the `DeInterpArray` like output). I do a lot of my own ODE work on a fixed grid, so I would miss the nice behavior you get from interfaces like matlab/Mathematica, where you can specify the output points you want and get an array. I guess if this is seen as not needed/not wanted, I would just need to always do `DEInterpArray(tstart:tend, sol(tstart:tend))` but that seems needlessly ugly.

Since at this point if you do `sol(tstart:tend)` you get back an array of arrays, and not just a flat array, so would it really be much more overhead to then wrap this in a `VectorOfArray` before it is returned? I am not sure what the buffer type means in this case (as it just seems to be making a `[interp(tval) for tval in tvals]` kind of loop before it returns it).

Bring the comments! I hope to add any features people might want!

**Comment by ChrisRackauckas** [comment]
>For the interp not returning anything but values, could we not just overload the solution call for when it gets a AbstractArray input of time points?

>Since at this point if you do sol(tstart:tend) you get back an array of arrays, and not just a flat array, so would it really be much more overhead to then wrap this in a VectorOfArray before it is returned?

That is a good point. Internal usage just grabs a points at single timepoints for things like event handling. 

>I do a lot of my own ODE work on a fixed grid, so I would miss the nice behavior you get from interfaces like matlab/Mathematica, where you can specify the output points you want and get an array.

Why not just use `saveat`? Then with the solution overloads, it will act like the array you want. This will be more efficient than interpolating afterwards too.

I think one thing that should also be included is a conversion function to a real contiguous matrix. This actually already exists, and is `vecvectomat` in RecursiveArrayTools.jl. It's just not documented in the DifferentialEquations.jl setup. But this should become something with a dispatch for VectorOfArray, and the DiffEq solution should be some form of a VectorOfArray.

**Comment by gabrielgellner** [comment]
I will add an overload to `vecvectomat` to get the dense array output. You can use the current interface with `vecarr[:, :, ..., :]` to do that, but it would be nicer to have `vecvectomat(vecarr)` to do the colons for you!

The only interface problem I have with using saveat (looking forward, as the current behavior doesn't seem to do what I want, namely it gives the internal save points, and the ones I ask for), is that I might want to refine my grid after, and if this turns off dense output, then I lose flexibility. At times I might want this for the speed increase, but I like have the interp version because it lets me do any kind of mesh refinement as I work.

**Comment by ChrisRackauckas** [comment]
>At times I might want this for the speed increase, but I like have the interp version because it lets me do any kind of mesh refinement as I work.

I see. That is a very good use of the interpolations. I never thought of doing that before.

>The only interface problem I have with using saveat (looking forward, as the current behavior doesn't seem to do what I want, namely it gives the internal save points, and the ones I ask for)

This probably needs some user input then if it confused you 👍 . Currently, it adds internal save points to the ones you ask for. You can turn off the extra points by setting `save_timeseries=false`, which will make it only save at the points you wanted (this will be renamed to `save_everystep=false`, which should be more obvious). But this will turn off density since you need the solver's timepoints saved to to the interpolations. The future `saveat` will set `save_everystep=false` by default, but the user can override this with `save_everystep=true` which would also re-enable interpolations, which themselves can be independently toggled with `dense=false` but are reliant on `save_everystep=true`.

Oh boy, the docs for that are a pain, but if you understand that you need the solver's timepoints to actually do the interpolation, but allow every possible combination, it makes sense. But this is https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/133 , comment there for more discussion.

**Comment by gabrielgellner** [comment]
I have added a function `vecarr_to_arr` to do the conversion (as just `vecvec_to_mat` seemed not as general as what we have now).

**Comment by ChrisRackauckas** [comment]
that's definitely a better name.

**Comment by ChrisRackauckas** [comment]
Looks like we aren't getting comments. I say we go for it. Make the change. This missed DiffEqBase v0.15.0 et. al. release (but that one is a mess of 10 packages changing concurrently), so lets aim for this + ParameterizedFunctions change from `dx` to `x_t` to be ecosystem v2.0

**Comment by gabrielgellner** [comment]
Sounds good. Are we a go for going with the `DEInterpArray` idea as well (basically the version that adds the time information to the returned object from a call to `sol(trange)`?

**Comment by ChrisRackauckas** [comment]
>Are we a go for going with the DEInterpArray idea as well (basically the version that adds the time information to the returned object from a call to sol(trange)?

That sounds good. That should be in DiffEqBase. I'll migrate RecursiveArrayTools.jl to JuliaDiffEq and add you to the Base group (but still PR this).

**Comment by gabrielgellner** [comment]
Perfect. Have you seen the RecursiveArrayTools PR? I will start doing the PR for DiffEqBase, once you are ready!

**Comment by ChrisRackauckas** [comment]
yeah, looking at it right now.

**Comment by ChrisRackauckas** [comment]
We might want to use this package for making the `...` in the indexing more explicit:

https://github.com/ChrisRackauckas/EllipsisNotation.jl
