### ISSUE TITLE
SDEProblem constructor questions

### ISSUE THREAD

**Issue by bradleyashton** [JuliaDiffEq/DifferentialEquations.jl#154]
1. If I read the documentation for 
SDEProblem(f,g,u0,tspan,noise=WHITE_NOISE,noise_rate_prototype=nothing)
over at http://docs.juliadiffeq.org/latest/types/sde_types.html#Fields-1
and use your comments from #145 

I interpret the syntax to mean:

If I want to solve a system of coupled complex variable SDEs driven by real noises, then to overcome the default behaviour of returning noises of the same type as the integrated type, I would do:

```Julia
import DiffEqBase.white_noise_func_wrapper!
@inline function white_noise_func_wrapper!(rand_vec,integrator)
  randn!(rand_vec)
end
prob = SDEProblem(f,g,a0,tspan,noise=WHITE_NOISE)
```
Is this correct?

2. What if I need essentially two different kinds of noise? In my case, I need the default white noise behaviour (complex valued noise for each complex variable), and then I need a separate NoiseProcess that is discussed here
http://docs.juliadiffeq.org/latest/features/noise_process.html#Noise-Processes-1
However, I need to use them both at different places in the same equation. How should I define `g` in this case?

**Comment by ChrisRackauckas** [comment]
Nope. It should be:

```julia
@inline function my_noise_function!(rand_vec,integrator)
  randn!(rand_vec)
end
my_noise = NoiseProcess{:White,true,typeof(my_noise_function!)}(my_noise_function!)
prob = SDEProblem(f,g,a0,tspan,noise=my_noise )
```

You need to build a `NoiseProcess` with the function you want. The docs for this might need a round 2.

If you need to mix different kinds of noises, you can just do that using views. For example, if the first `N` variables should use the complex Wiener process, you can just pass through to the default:

```julia
const N = ... # should declare it as a constant for speed, or enclose it in the function
@inline function my_noise_function!(rand_vec,integrator)
  DiffEqBase.white_noise_func_wrapper!(@view(rand_vec[1:N]),integrator)
  randn!(@view(rand_vec[(N+1):end]))
end
my_noise = NoiseProcess{:White,true,typeof(my_noise_function!)}(my_noise_function!)
prob = SDEProblem(f,g,a0,tspan,noise=my_noise )
```

Or instead of `DiffEqBase.white_noise_func_wrapper!(@view(rand_vec[1:N]),integrator)`, You can just do `DiffEqBase.wiener_randn!(@view(rand_vec[1:N]))`. Just some way that throws that part of the vector to the `randn!` in DiffEqBase. 

Or if you want to do it without referring at all to the internal functions, you can just

```julia
const N = ... # should declare it as a constant for speed, or enclose it in the function
@inline function my_noise_function!(rand_vec,integrator)
  for i in 1:N
    rand_vec[i] = (randn() + im*randn())/sqrt(2)
  end
  randn!(@view(rand_vec[(N+1):end])) # or loop here too!
end
my_noise = NoiseProcess{:White,true,typeof(my_noise_function!)}(my_noise_function!)
prob = SDEProblem(f,g,a0,tspan,noise=my_noise )
```

**Comment by bradleyashton** [comment]
Ok, MWE throwing error (What I am trying to test is: can I make the first noise the default (in this case complex), and then the second real):

```Julia
using DifferentialEquations
#system parameters
γ = 1.
χ = .01

#elements of u, f g are complex vars
f=function (t,u,du) 
    du[1] = -(γ + 2*im*χ*u[1]*u[2])u[1] 
    du[2] = -(γ - 2*im*χ*u[1]*u[2])u[2] 
end  

g=function(t,u,du)
    du[1] = sqrt(-2*im*χ*u[1]^2)
    du[2] = sqrt(2*im*χ*u[2]^2)
end

const N = 1 # should declare it as a constant for speed, or enclose it in the function
@inline function my_noise_function!(rand_vec,integrator)
  DiffEqBase.white_noise_func_wrapper!(@view(rand_vec[1:N]),integrator)
  randn!(@view(rand_vec[(N+1):end]))
end
my_noise = NoiseProcess{:White,true,typeof(my_noise_function!)}(my_noise_function!)

ti=0.
tf=1.
Nt=100
tspan = (ti,tf)
t=collect(linspace(ti,tf,Nt))
a0 = randn(2)+im*randn(2)
prob = SDEProblem(f,g,a0,tspan,noise=my_noise)
alg = EM()
dt=1/1e3

sol = solve(prob,alg,dt=dt,saveat=t,save_everystep=false)

MethodError: no method matching randn(::MersenneTwister, ::Type{Complex{Float64}})
Closest candidates are:
  randn{T}(::AbstractRNG, ::Type{T}, ::Tuple{Vararg{Int64,N}}) at random.jl:1216
  randn{T}(::AbstractRNG, ::Type{T}, ::Integer, ::Integer...) at random.jl:1218
  randn(::AbstractRNG) at random.jl:1129
  ...

 in randn!(::MersenneTwister, ::SubArray{Complex{Float64},1,Array{Complex{Float64},1},Tuple{UnitRange{Int64}},true}) at ./random.jl:1208
 in (::DiffEqBase.NoiseProcess{:White,true,#my_noise_function!})(::Array{Complex{Float64},1}, ::StochasticDiffEq.SDEIntegrator{StochasticDiffEq.EM{StochasticDiffEq.RSWM
...
```

**Comment by ChrisRackauckas** [comment]
It had a hiccup at `randn!(@view(rand_vec[(N+1):end]))` because `rand_vec` was a vector of `Complex128`. It very ungracefully was calling the wrong method... this is actually the same issue in the first place. We can just avoid this all together:

```julia
@inline function my_noise_function!(rand_vec,integrator)
  DiffEqBase.white_noise_func_wrapper!(@view(rand_vec[1:N]),integrator)
  for i in (N + 1):length(rand_vec)
    rand_vec[i] = randn()
  end
end
```

That works. `rand_vec[i] = randn()` auto-promotes the result to a complex with 0 imaginary part. We can do this the very explicit way instead:

```julia
@inline function my_noise_function!(rand_vec,integrator)
  for i in 1:N
    rand_vec[i] = (randn() + im*randn())/sqrt(2)
  end
  for i in (N + 1):length(rand_vec)
    rand_vec[i] = randn()
  end
end
```

Note that something which is annoying is that Plots.jl cannot handle complex numbers. You can use the [function plotting]() stuff to handle this:

```julia
real_part = (x,y) -> (x,real(y))
im_part = (x,y) -> (x,imag(y))
using Plots; plot(sol,vars=[(real_part,0,1),(im_part,0,1),(real_part,0,2),(im_part,0,2)])
```

![newplot 21](https://cloud.githubusercontent.com/assets/1814174/25054667/57e2f5c6-2113-11e7-8447-f263c78c459a.png)

But instead a recipe should be made for Plots.jl to automatically split complex numbers.

**Comment by bradleyashton** [comment]
Ok this is great, thanks a lot for this, it all seems to be working nicely! To help people get started it could be worthwhile to give some more detailed examples in the documentation. 

One thing I can't track down in the docs: how do I get the solution to save in a reasonable way, instead of just occupying memory? With lots of trajectories one pretty quickly hits a natural hardware limit.

**Comment by ChrisRackauckas** [comment]
>To help people get started it could be worthwhile to give some more detailed examples in the documentation.

This is probably a good example. Any others that you can think of? Would you be interested in contributing some? It just builds itself from the Markdown file:

https://github.com/JuliaDiffEq/DiffEqDocs.jl/blob/master/docs/src/features/noise_process.md

The `NoiseProcess` part is definitely in need of more in-depth docs, but what I showed there is pretty much all there is to it. So doing some standard things like correlated noise is just about finding out how to generate a random vector appropriately.

I think another thing that would help would be to have helpers for very standard forms of noise. Pink noise, 1/f noise, etc. I have something that generates correlated white noise according to a constant covariance matrix. It's currently undocumented, but you can see here:

https://github.com/JuliaDiffEq/DiffEqBase.jl/blob/master/src/noise_process.jl#L48

that it creates the function for generating correlated noise just by using the SVD factorization of the covariance matrix. These kinds of helpers should also get documented in the noise process docs, and it would make this much easier than simply doing the low-level calculations.

>One thing I can't track down in the docs: how do I get the solution to save in a reasonable way, instead of just occupying memory? With lots of trajectories one pretty quickly hits a natural hardware limit.

What do you mean? This page explains the options:

http://docs.juliadiffeq.org/latest/basics/common_solver_opts.html#Output-Control-1

while this page gives some more details:

http://docs.juliadiffeq.org/latest/features/output_specification.html

The second one might be in need of an update. It probably just needs a bunch of examples for how to setup a bunch of different ways to refine how much is saved. Someone already volunteered to do that. But yes, you can go all the way to make it only save the final timepoint if you want.

**Comment by bradleyashton** [comment]
so by saving I mean: sequentially save to file and clear resident memory. At the moment `sol` just sits in RAM I think, or have missed something here? Say I run 10^6 trajectories. Do I just need to run and save separate batches that fit within the RAM limits? Maybe I need to understand more about how monteCarlo works

**Comment by bradleyashton** [comment]
regarding docs, I am getting together a couple of examples that run through the whole workflow, so maybe I can contribute something there

**Comment by ChrisRackauckas** [comment]
>At the moment sol just sits in RAM I think, or have missed something here? Say I run 10^6 trajectories. Do I just need to run and save separate batches that fit within the RAM limits?

Oh yes, I don't have saving out to files yet. I just opened an issue not too long ago to start brainstorming that:

https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/151

For now I've just been avoiding it by using the output controls. There's two levels there. I mentioned already that you can control how much is saved during a run. Most MonteCarlo things I do, I only need the endpoint or something like that, so using the output controls helps there a lot. In addition, the MonteCarlo has a reduction function `output_func`:

http://docs.juliadiffeq.org/latest/features/monte_carlo.html#Building-a-Problem-1

(this might need expanded docs too, also very new and improved)

Essentially, what I can do is tell the solver:

1) During the run, only save the endpoint (or only save "x", and you can get very specific here)
2) After each run, only save `output_func(sol)`. So I can do some analysis, like calculate the mean.
3) The MonteCarlo function saves the array of the `output_func(sol)` outputs. So if I calculated the mean in the `output_func`, then what you'll get back as the `solution_data` is the 10^6 different means for each separate trajectory.

So since you're controlling it at that level, you can make it so that way at most you have to store `# of cores` solutions at any given time, and try to cut down and do the analysis at each point that you can.

Obviously this doesn't handle every case, but when that works you can keep everything in RAM and do very well. But if we have what's proposed in https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/151, then you can do something like serialize the solution after each run, which can greatly expand this. 

I'm not quite sure what a DiffEqIO.jl really needs, so feel free to start discussing more details there.

**Comment by ChrisRackauckas** [comment]
@bradleyashton I put a PR into Plots.jl to give it native handling of complex arrays:

https://github.com/JuliaPlots/Plots.jl/pull/774

That will make the plotting situation easier.

**Comment by bradleyashton** [comment]
This might be a naive question, but:

If I read the docs, I find under parallelism:

`Since this is using pmap internally, it will use as many processors as you have Julia processes. To add more processes, use addprocs(n). See Julia's documentation for more details.`

However, if I do `addprocs(1)` on my dual core machine, and then run `sol = solve(...)` as before, I get the error:
```julia
On worker 2:
UndefVarError: DiffEqMonteCarlo not defined
 in deserialize at ./serialize.jl:602
 in handle_deserialize at ./serialize.jl:581
 in deserialize at ./serialize.jl:541
 in deserialize_datatype at ./serialize.jl:824
 in handle_deserialize at ./serialize.jl:571
 in deserialize_msg at ./multi.jl:120
 in message_handler_loop at ./multi.jl:1317
 in process_tcp_streams at ./multi.jl:1276
 in #638 at ./event.jl:68
```

am I interpreting this correctly that I should expect parallel processing with no further commands if I add props to the local machine?

**Comment by ChrisRackauckas** [comment]
See https://docs.julialang.org/en/stable/manual/parallel-computing/

You need to `@everywhere using DifferentialEquations`. It's just not finding the module on the other process.

**Comment by ChrisRackauckas** [comment]
This kind of transformed into the other issues.
