### ISSUE TITLE
Rosenbrock doesn't work for systems

### ISSUE THREAD

**Issue by robertdj** [JuliaDiffEq/DifferentialEquations.jl#158]
Hi

Trying out the DiffEq packages, that are very impressive!

However, I run into a problem (with the ForwardDiff package; unsure where to open the issue) when using the `Rosenbrock23` method for systems. 

Consider e.g. this example from [the docs](http://docs.juliadiffeq.org/stable/tutorials/ode_example.html#Systems-of-Equations-1):
```julia
A = [1. 0 0 -5
     4 -2 4 -3
     -4 0 0 1
     5 -2 2 3]
u0 = rand(4,1)
tspan = (0.0,1.0)
f(t,u) = A*u
prob = ODEProblem(f,u0,tspan)
sol = solve(prob, Rosenbrock23())
```
Resulting in an error:
```julia
ERROR: MethodError: no method matching one(::Array{Float64,1})
...
in derivative at ~/.julia/v0.5/ForwardDiff/src/derivative.jl:5
```

**Comment by ChrisRackauckas** [comment]
Fixed on master. It'll take a few days for it to get released.

But this is more of a documentation problem. If you use the in-place form:

```julia
using DiffEqBase, OrdinaryDiffEq

A = [1. 0 0 -5
     4 -2 4 -3
     -4 0 0 1
     5 -2 2 3]
u0 = rand(4)
tspan = (0.0,1.0)
function f(t,u,du)
  A_mul_B!(du,A,u)
end
prob = ODEProblem(f,u0,tspan)
sol = solve(prob, Rosenbrock23())

using Plots; plot(sol)
```

it works just fine on current release. And usually for systems of equations you want to use the inplace form `f(t,u,du)` for performance instead of the out of place form `f(t,u)`. I wonder if that example in the tutorial should be replaced since it seems quite a few people end up writing in the out of place form for systems. But the convenience cannot be understated.

**Comment by robertdj** [comment]
Thanks!

A bit off-topic: Is this Rosenbrock23 algorithm the same as the one used in Matlab's `ode23s`? 
I'm curious because the Julia code runs so much faster :-)

**Comment by ChrisRackauckas** [comment]
It's a very similar algorithm. Same coefficients, but I don't think Shampine's code uses a possible FSAL in there. Also, autodifferentiation helps quite a bit: Rosenbrock methods require very precise Jacobians, and autodifferentiation will get close to machine error while numerical differentiation (which MATLAB uses) will decrease the accuracy, sometimes actually reducing the order of the method. I think that's where the main differences are, and I've been studying this implementation to death before implementing the higher order Rosenbrock methods.

**Comment by robertdj** [comment]
Great! Thanks a lot!
