### ISSUE TITLE
Extract solution as function

### ISSUE THREAD

**Issue by robertdj** [JuliaDiffEq/DifferentialEquations.jl#159]
From a solution to a system of equations, I want to extract one component as a **function**.
Since a solution object evaluates at all points in the specified interval with interpolations this works:
```
A = [1. 0 0 -5
     4 -2 4 -3
     -4 0 0 1
     5 -2 2 3]
u0 = rand(4,1)
tspan = (0.0,1.0)
f(t,u) = A*u
prob = ODEProblem(f,u0,tspan)
sol = solve(prob)
g(t) = sol(t)[1]
```
However, it also consumes quite some resources and it makes me wonder if there is a better way?

(I suspect that the memory consumption is due to fact that `sol(t)` returns a vector before picking out a single element, but maybe the interpolation requires something as well?)

**Comment by ChrisRackauckas** [comment]
http://docs.juliadiffeq.org/latest/basics/solution.html#Interpolations-1

```julia
sol(t;idxs=i)
```

for the `i`th component, or 

```julia
sol(out,t)
```

where `out` is a pre-allocated array.

**Comment by robertdj** [comment]
Nice. However, the reason why I want to extract a component is to use it as an input in another `ODEProblem`. Then I get an (long) error message that ends with

```
ERROR: LoadError: MethodError: Cannot `convert` an object of type ForwardDiff.Dual{1,Float64} to an object of type Float64
This may have arisen from a call to the constructor Float64(...),
since type constructors fall back to convert methods.
 in ode_interpolant! at ~/.julia/v0.5\OrdinaryDiffEq/src/dense/interpolants.jl:55 [inlined]
```

Let me see if I can come up with a MWE.

**Comment by ChrisRackauckas** [comment]
Are you autodifferentiating something? It looks like a problem due to changing types to dual numbers. You want to create a new problem if you're changing types.

**Comment by robertdj** [comment]
With the notation from above, I want something along the lines of:
```
function h(t,u,du)
du[1] = u
du[2] = sol(t; idxs=1)
end

prob2 = ODEProblem(h, ones(2), tspan)
sol2 = solve(prob2)
```

I know I can combine the two systems/`prob`s into one, but if possible I would like to break it into pieces like this.

**Comment by ChrisRackauckas** [comment]
That should work.

**Comment by robertdj** [comment]
The code with `prob2`? That's where I get an error... 

Maybe it's a problem with out-of-date packages on my computer -- I'll try to update tomorrow.

**Comment by ChrisRackauckas** [comment]
That's where you get the autodifferentiation error? Then you should try using an algorithm which doesn't require autodifferentition. Try an explicit RK method like `Tsit5()`, or use `CVODE_BDF()` on the interpolated solution (the first solution can't use Sundials here since it doesn't return an interpolation).

**Comment by ChrisRackauckas** [comment]
Any update on this?

**Comment by robertdj** [comment]
If I understand your suggestion correctly you want to replace 
```
sol2 = solve(prob2)
```
with
```
sol2 = solve(prob2, CVODE_BDF())
```
and leave everything else untouched? That doesn't work for me.

**Comment by ChrisRackauckas** [comment]
Can I get a full example? I'm not sure where you're autodifferentiating.

**Comment by robertdj** [comment]
Sorry about my long absence! I haven't had access to a computer the last couple of days.

While pasting everything into one file I found a solution: Making an in-place method of the `bar` function.

```
using DifferentialEquations

A = [1. 0 0 -5
     4 -2 4 -3
     -4 0 0 1
     5 -2 2 3]
u0 = rand(4)
tspan = (0.0,1.0)
bar(t,u) = A*u
bar(t,u,du) = A_mul_B!(du, A, u)
prob = ODEProblem(bar, u0, tspan)
sol1 = solve(prob)

function foo(t,u,du)
    du[1] = u[1]
    du[2] = sol1(t; idxs=1)
end

prob2 = ODEProblem(foo, ones(2), tspan)
sol2 = solve(prob2)
```

**Comment by robertdj** [comment]
Sorry about my long absence! I haven't had access to a computer the last couple of days.

This is a full (non-working) example:
```
using DifferentialEquations

A = [1. 0 0 -5
     4 -2 4 -3
     -4 0 0 1
     5 -2 2 3]
u0 = rand(4)
tspan = (0.0,1.0)
bar(t,u,du) = A_mul_B!(du, A, u)
prob = ODEProblem(bar, u0, tspan)
sol1 = solve(prob)

function foo(t,u,du)
    du[1] = u[1]
    du[2] = sol1(t; idxs=1)
end

prob2 = ODEProblem(foo, ones(2), tspan)
sol2 = solve(prob2, Rosebrock23())
```

I have tried adding an `foo(::Type{Val{:jac}},t,u,J)` method in an attempt to avoid the autodifferentiation, but to no avail.

**Comment by ChrisRackauckas** [comment]
>I have tried adding an foo(::Type{Val{:jac}},t,u,J) method in an attempt to avoid the autodifferentiation, but to no avail.

It's failing in the `tgrad` computation, not the Jacobian computation. The Jacobian one should be fine. Taking the derivative in `t` using autodifferentiation puts a Dual number into `sol1(t; idxs=1)`. That's the issue. I'll investigate whether this is possible to fix, but sometimes operator overloaded autodifferentiation will hit something that is just impossible, and this may be one of those cases. The only thing to do in that case would be to supply the t-gradient function, or not use autodifferentiation. The `autodiff=false` flag in Rosenbrock methods was disabled a bit a go to make the refactoring to DiffEqDiffTools.jl (@miguelraz 's GSoC project) have a simpler start. But once that's up and running, there will be a non-autodifferentiation option again that will work here. For now, you can use `radau()` just fine though. Sundials doesn't seem to work here because of https://github.com/JuliaDiffEq/Sundials.jl/issues/105 (it steps past the actual end of the integration and interpolates back... Sundials' default behavior is peculiar)

**Comment by robertdj** [comment]
That makes sense. 

Is it possible to do make a `foo(::Type{Val{:tgrad}},t,u,J)` method where I provide the explicit `t` gradient for the entry with `sol1(t; idxs=1)` and let autodifferentiation handle the rest?

**Comment by ChrisRackauckas** [comment]
>Is it possible to do make a foo(::Type{Val{:tgrad}},t,u,J) method where I provide the explicit t gradient for the entry with sol1(t; idxs=1) and let autodifferentiation handle the rest?

With direct calls to ForwardDiff yes.

**Comment by robertdj** [comment]
Testing if a (wrong) `tgrad` fixes the problem. I still get the same kind of error if I add e.g.
```
function foo(::Type{Val{:tgrad}}, t, u, J)
    J[1] = 1.5
    J[2] = 1.0
    nothing
end
```

**Comment by ChrisRackauckas** [comment]
Ugh, it's because `Rosenbrock23()` isn't able to properly use t-grad on release+master because of the refactor. We need DiffEqDiffTools.jl in order to enable that again (otherwise it's a monstrosity of repeated code).

The temporary fix is to have the second `solve` use `radau`. I'll see what else I can get working

**Comment by ChrisRackauckas** [comment]
Okay, I took a good look at it. While the error could be moved further down the line, this (solution interpolation autodifferentiated in the next solution) for very fundamental reasons will never work. Essentially, the type from the interpolation is not and cannot be determined from the type of `t`, since all of the values that build it match the type from the value that built the solution to be interpolated. Solving the `sol1` with an array of Dual numbers I think would lead to perturbation clashing, so this is just not possible.

But, manual `tgrad` and turning off autodifferentiation in this case are good ideas, but got "unimplemented" for the pending DiffEqDiffTools changes. I will keep this issue open until those workarounds are back.

**Comment by robertdj** [comment]
I'm having some problems controlling time steps with `radau`
```
sol2 = solve(prob2, radau())
```
gives a very crude estimate of the solution and so does
```
sol2 = solve(prob2, radau(); dt=1//2^4)
```
I've been reading the documentation for quite some time, but I can't seem to find a workaround. 

Also, I'm surprised that `radau` works out of the box -- in the documentation is says that 
> For faster solving when the Jacobian is known, use `radau`

but I haven't specified a a `jac`/`tgrad` function.

Thanks for all your time!

**Comment by ChrisRackauckas** [comment]
>sol2 = solve(prob2, radau(); dt=1//2^4)

http://docs.juliadiffeq.org/latest/basics/common_solver_opts.html#Stepsize-Control-1

>dt: Sets the initial stepsize. This is also the stepsize for fixed timestep methods. Defaults to an automatic choice.

That only sets the **initial stepsize**. In general, adaptive timestepping methods are controlled via tolerances. For example:

```julia
sol2 = solve(prob2, radau();abstol=1e-9,reltol=1e-9)
```

is a good way to get a much more tightly controlled solution.

**Comment by robertdj** [comment]
Something that's a little strange when using `radau`: The `interp` parts of the solution doesn't work.
```
julia> sol2(0.4)
ERROR: MethodError: no method matching (::DiffEqBase.##23#25)(::Float64, ::Void, ::Type{Val{0}})
Closest candidates are:
  #23(::Any) at C:\Users\69350\.julia\v0.5\DiffEqBase\src\solutions/ode_solutions.jl:34
 in (::DiffEqBase.ODESolution{Array{Array{Float64,1},1},Array{Float64,1},Array{Any,1},DiffEqBase.ODEProblem{Array{Float64,1},Float64,true,#foo},ODEInterfaceDiffEq.radau,DiffEqBase.##23#25})(::Float64) at C:\Users\69350\.julia\v0.5\DiffEqBase\src\solutions\ode_solutions.jl:13

julia> sol2.interp # With radau
(::#23) (generic function with 1 method)

julia> sol2.interp # With Rosenbrock23
(::InterpolationData) (generic function with 2 methods)
```

(The solution can be extracted using e.g. `[u[1] for u in sol.u]`, but I'm curious about why this doesn't work.)

**Comment by ChrisRackauckas** [comment]
The ODEInterface algorithms will never be compatible with post-solution interpolation. The chart notes that it's not implemented for that package:

http://docs.juliadiffeq.org/latest/basics/compatibility_chart.html

But by design, I don't believe there is a way to save its density information for post-solution interpolation. (This is one of the big reasons why the next step is a native Julia `radau`). I added a better error message for this case. 

Since it looks like this is important and this will help the DiffTools, I'll get some of the `jac` and `tgrad` stuff back in Rosenbrock and let you know when.

**Comment by robertdj** [comment]
Great -- thanks a lot!

**Comment by ChrisRackauckas** [comment]
Alright, I setup the full `Rosenbrock23()` (since that's pretty critical). This works now:

```julia
using DifferentialEquations

A = [1. 0 0 -5
     4 -2 4 -3
     -4 0 0 1
     5 -2 2 3]
u0 = rand(4)
tspan = (0.0,1.0)
bar(t,u,du) = A_mul_B!(du, A, u)
prob = ODEProblem(bar, u0, tspan)
sol1 = solve(prob)


function foo(t,u,du)
    du[1] = u[1]
    du[2] = sol1(t; idxs=1)
end

function foo(::Type{Val{:tgrad}}, t, u, J)
    J[1] = 1.5
    J[2] = 1.0
    nothing
end

prob2 = ODEProblem(foo, ones(2), tspan)
sol2 = solve(prob2, Rosenbrock23())
```

In addition, this can work:

```julia
function foo2(t,u,du)
    du[1] = u[1]
    du[2] = sol1(t; idxs=1)
end

prob2 = ODEProblem(foo2, ones(2), (0.0,1.0))
sol2 = solve(prob2, Rosenbrock23(autodiff=false))
```

If you do this directly, you'll get an error that the solution cannot extrapolate. This is because it's using finite differences (central difference), so it needs a time point just before `0.0` (`t = -6.0554544523933395e-6`) to exist in the solution. If you can't get a time point before, you can change to using forward differences. Full example:

```julia
using DifferentialEquations

A = [1. 0 0 -5
     4 -2 4 -3
     -4 0 0 1
     5 -2 2 3]
u0 = rand(4)
tspan = (0.0,1.0)
bar(t,u,du) = A_mul_B!(du, A, u)
prob = ODEProblem(bar, u0, tspan)
sol1 = solve(prob)


function foo(t,u,du)
    du[1] = u[1]
    du[2] = sol1(t; idxs=1)
end

function foo(::Type{Val{:tgrad}}, t, u, J)
    J[1] = 1.5
    J[2] = 1.0
    nothing
end

prob2 = ODEProblem(foo, ones(2), tspan)
sol2 = solve(prob2, Rosenbrock23())

function foo2(t,u,du)
    du[1] = u[1]
    du[2] = sol1(t; idxs=1)
end

prob2 = ODEProblem(foo2, ones(2), (0.0,1.0))
sol2 = solve(prob2, Rosenbrock23(autodiff=false,diff_type=:forward))
```

In addition, making sure the first solution is slightly over-solved will make Sundials work. Example:

```julia
using DifferentialEquations

A = [1. 0 0 -5
     4 -2 4 -3
     -4 0 0 1
     5 -2 2 3]
u0 = rand(4)
tspan = (0.0,2.0)
bar(t,u,du) = A_mul_B!(du, A, u)
prob = ODEProblem(bar, u0, tspan)
sol1 = solve(prob)

function foo(t,u,du)
    @show t
    du[1] = u[1]
    du[2] = sol1(t; idxs=1)
end

using Sundials
prob2 = ODEProblem(foo, ones(2), (0.0,1.0))
sol2 = solve(prob2, CVODE_BDF())
```

Sundials doesn't have post-solution interpolation, but it does have `saveat`. 


I will release the complete version of Rosenbrock right away and add the choice of differencing to the docs. I hope this doesn't step on @miguelraz 's project too much, but hey, there's infinitely many interesting things to do.

**Comment by ChrisRackauckas** [comment]
The stuff that is possible (using finite differencing instead of autodiff, and passing `tgrad` etc.) is now available in OrdinaryDiffEq.jl. Docs are up too:

http://docs.juliadiffeq.org/latest/solvers/ode_solve.html#Extra-Options-1

Let me know if you have any other questions.

**Comment by robertdj** [comment]
Wow! You're fast! 

Thanks a lot -- I'll check out the new options.

**Comment by robertdj** [comment]
I suppose this is more of a usage question: The `tgrad` function doesn't seem to have any influence on the solution. The function **is** called, but the solution looks the same regardless of what I fill into `J`.

```
using DifferentialEquations
using Plots

function f(t ,u ,du)
    du[1] = 2.0 * u[1] - 1.2 * u[1]*u[2]
    du[2] = -3 * u[2] + u[1]*u[2]
end

function f(::Type{Val{:tgrad}} ,t ,u ,J)
    # fill!(J, 0.0)
    # J[1] = 1.0; J[2] = -1.0
    fill!(J, randn())
    nothing
end

prob = ODEProblem(f, ones(2), (0.0, 10.0))
sol = solve(prob, Rosenbrock23())
plot(sol)
```

**Comment by ChrisRackauckas** [comment]
Uhh, it's clearly doing something.

```julia
using DiffEqBase, OrdinaryDiffEq
using Plots

function f(t ,u ,du)
    du[1] = 2.0 * u[1] - 1.2 * u[1]*u[2]
    du[2] = -3 * u[2] + u[1]*u[2]
end

function f(::Type{Val{:tgrad}} ,t ,u ,J)
    # fill!(J, 0.0)
    # J[1] = 1.0; J[2] = -1.0
    fill!(J, 30)
    nothing
end

prob = ODEProblem(f, ones(2), (0.0, 10.0))
sol = solve(prob, Rosenbrock23(),adaptive=false,dt=1/4)
plot(sol)
```

![newplot 6](https://cloud.githubusercontent.com/assets/1814174/26377079/b0677f68-3fc3-11e7-9953-5fb98951396c.png)


The time-gradient correction is just a small term, since most of it is captured by the function call. This also already has a test:

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/test/differentiation_traits_tests.jl

**Comment by robertdj** [comment]
I was missing the `adaptive` keyword... Sorry about all these stupid questions -- I didn't find that option in the docs. 

One more question: I would like to step into the solver with e.g. the above code. But with
```
Gallium.breakpoint("~/.julia/v0.5/OrdinaryDiffEq/src/integrators/rosenbrock_integrators.jl", 23)
```
I don't get into that function/file. Is it the right file?

**Comment by ChrisRackauckas** [comment]
`adaptive` isn't needed there. That's just to fix the stepsize and make it obvious. It's still being used when the stepsize isn't adaptive, but since that's not the correct gradient, the error handling will detect that and decrease the stepsizes to make this error less noticeable. Essentially the stuff that's there to correct for errors will correct your intentional error.

>One more question: I would like to step into the solver with e.g. the above code. But with

That should be the right file. I am not sure about Gallium and breakpoints: I am not sure that works quite yet.
