### ISSUE TITLE
How many batteries to include in the batteries included approach?

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DifferentialEquations.jl#168]
DifferentialEquations.jl is about the batteries-included approach to JuliaDiffEq where the manual should just work, and anything that isn't included is explicitly mentioned in the docs. Right now, the only things which are not explicitly included are the interop libraries which require a compiler (DASKR, LSODA, ODEInterfaceDiffEq) and deprecated Julia packages. 

However, should we extend this a little bit? Should PyDSTool be something not automatically installed? It seems like it has the chance of giving build failures and can be quite big. Should the future FEniCS addon be in this same boat as well? For these, their docs pages, as addons, can just lead with "Needs to be installed separately. `Pkg.add ... and using`". So I think we can get away with this pretty easily.

SymEngine I think is on the other side of the line because it's required for ParameterizedFunctions, and from around the ecosystem I know that the use of those macros is pretty core DiffEq usage. So I don't think a SymEngine-free DifferentialEquations.jl is a possibility. 

What about taking the DiffEq.jl name as a DiffEqBase + native Julia solvers only shorthand?

I think we need to refine the idea of DifferentialEquations.jl now because at first "all that is possible" was okay since not too much was possible. Now, "all that is possible" is quite large.

@aytekinar

**Comment by aytekinar** [comment]
Personally, I have allergy against `Py*` packages. I mean, writing wrappers for python libraries and benefiting from already mature libraries is important. However, if one can write the solution in a julian way, it should be julian. it is more expressive, it is cleaner, etc. and I cannot consider myself as a good python programmer, either. I do not understand all that `pip`, `conda`, `miniconda` stuff. Plus, I have had trouble on my Arch linux installation while using `PyPlot` due to the conflicts in the backends matplotlib was using.

In short, I would love to have `DiffEq` type of solution. I can `REQUIRE` any base package in my approaches, and then later on, `Pkg.add` whatever package can connect to those base packages. And, if I have the solution already in native julia, this is simply great! I don't need to install external libraries, and I can simply understand (hopefully to some extent) what's going on inside that code/package.

if this is what you meant, I am for such an approach. I might need ODE solvers and some delayed equation solvers, though I have not worked with delayed systems explicitly. And, in discrete systems, delayed system representations are much easily handled than in their continuous counterparts.

**Comment by ChrisRackauckas** [comment]
The newest release got rid of PyDSTool, meaning there's not Python interop packages. Only non-native Julia code is now from Sundials and SymEngine (via ParameterizedFunctions). Those are too core to take out.

The idea of a DiffEq.jl should still be on the table though. But I don't know how useful that actually is?

**Comment by aytekinar** [comment]
As far as I am concerned, for instance, `DiffEqBase` is light-weight enough. `OrdinaryDiffEq` also is lightweight, and they together solve my problems in a neat way for now. Thanks for all the hard work! 👍

**Comment by musm** [comment]
> What about taking the DiffEq.jl name as a DiffEqBase + native Julia solvers only shorthand?

I really like this suggestion. Other than:
DiffEqBase.jl
StochasticDiffEq.jl
OrdinaryDiffEq.jl
what would it include?

**Comment by ChrisRackauckas** [comment]
DelayDiffEq.jl? SteadyStateDiffEq.jl? I think that's it. It would be the same as:

```julia
using DiffEqBase, OrdinaryDiffEq, StochasticDiffEq, DelayDiffEq, SteadyStateDiffEq
```

which would give you all of the native solvers (the `*DiffEq`) which handles most basic use cases.

**Comment by musm** [comment]
I'ma fan I hope such a minimization would then automatically allow the package for inclusion in JuliaPro

To recap 
```
DiffEqBase.jl
AlgebraicDiffEq.jl
StochasticDiffEq.jl
OrdinaryDiffEq.jl
DelayDiffEq
SteadyStateDiffEq
```

**Comment by ChrisRackauckas** [comment]
>AlgebraicDiffEq.jl

That one is essentially deprecated and turned into a blank repo, but yeah that's the idea.

**Comment by ChrisRackauckas** [comment]
>I'ma fan I hope such a minimization would then automatically allow the package for inclusion in JuliaPro

We've already talked about including DifferentialEquations.jl. I think that's a better idea because the docs fully comply with it, and because I believe they will want Sundials.jl with it. Someone is supposed to be working on making this happen... I forget who.

**Comment by musm** [comment]
In any case should probably wait until Pkg3 announcement

**Comment by ChrisRackauckas** [comment]
Yeah for sure.
