### ISSUE TITLE
saveat not working for a matrix of linear ODE

### ISSUE THREAD

**Issue by Paulms** [JuliaDiffEq/DifferentialEquations.jl#175]
from documentation example:

```julia
A = [1. 0 0 -5
     4 -2 4 -3
     -4 0 0 1
     5 -2 2 3]
u0 = rand(4,2)
tspan = (0.0,1.0)
f(t,u) = A*u
prob = ODEProblem(f,u0,tspan)
sol = solve(prob,SSPRK22();saveat=0.1, dt=0.01)
```
It displays the following error:
```repl
MethodError: Cannot `convert` an object of type Array{Float64,1} to an object of type Float64
```
saveat works as expected with normal problems and the same SSPRK22 algorithm:

```julia
α=1
u0=1/2
f(t,u) = α*u
tspan = (0.0,1.0)
prob = ODEProblem(f,u0,tspan)
sol = solve(prob, SSPRK22();saveat=0.1,dt=0.01)
```

Version info:
```julia
Pkg.installed("DifferentialEquations")
v"2.2.1"
```

**Comment by ChrisRackauckas** [comment]
This is working on my current branch, but will be released as v0.6 only (since its a big re-write of the interpolations to use broadcast). So that's good! I'll try to get this released by the end of the weekend.

But, on v0.5 this will still work if you make it inplace:

```julia
using OrdinaryDiffEq, DiffEqBase
A = [1. 0 0 -5
     4 -2 4 -3
     -4 0 0 1
     5 -2 2 3]
u0 = rand(4,2)
tspan = (0.0,1.0)
f(t,u,du) = A_mul_B!(du,A,u)
prob = ODEProblem(f,u0,tspan)
sol = solve(prob,SSPRK22();saveat=0.1, dt=0.01)
```

For performance you should be using the inplace version on vector equations anyways. Does the tutorial not do a good job at explaining that? This is the second question this week where the issue was with out-of-place solving on array equations. While I want to make sure that works correctly, it should be very rare that combination is actually used.

**Comment by Paulms** [comment]
Thanks!, It is good to know that works with in-place version. Actually, I am planning to use in-place with my real problem, but first I was just trying some ideas, I didn't realize that the error was only in this case

**Comment by ChrisRackauckas** [comment]
Yeah, the inplace versions have a ton of tests for just about everything. Out-of-place tests for just about everything, but with `u0` being a number.

Out-of-place on array types didn't really have much of a use-case, so there are still a few areas where tests didn't hit (since there are a few spots where out-of-place need a separate code path to deal with the lack of mutability, and sometimes those accidentally assume the user is using some immutable number type). However, since StaticArrays actually are immutable arrays that have to be used out-of-place (but aren't stack-allocated so it's efficient to do so), this now has a very useful application, so I'm going through make sure all of that gets tested and works well. Current master deals with most of the issues in this spot.

**Comment by ChrisRackauckas** [comment]
Works on latest OrdinaryDiffEq.jl release, though that is v0.6 only.
