### ISSUE TITLE
Higher order solvers for non-diagonal noise

### ISSUE THREAD

**Issue by onoderat** [JuliaDiffEq/DifferentialEquations.jl#200]
I have been attempting to run a higher order sde solver with my own noise process (real wiener process). The current test case is as follows. 

Could you advice on what higher order solvers are available for non-diagonal noise and what to set the Z0 for that solver? For a test case, I am running the following SDE below where the variable is 2 dimensional while the noise is 1 dimensional. 

using DifferentialEquations

function f(t,u,du)
    du[1] = im*u[1]
    du[2] = u[2]
end

function g(t, u, du)
    du[1,1] = 0.1*u[1]
    du[2,1] = 0.2*im
end

dt = 1e-3
tspan = (0.0,1.0)
u₀=complex([1., 1.])
W = RealWienerProcess(0.0,[0.],[0.]) # <- where the problem is

prob = SDEProblem(f,g,u₀,(0.0,1.0),noise_rate_prototype=complex(zeros(2,1)), noise=W)
sol = solve(prob, SRIW1(), dt=dt, adaptive=false)

**Comment by ChrisRackauckas** [comment]
The current high order methods are for diagonal noise only. There are open issues for non diagonal additive and scalar noise cases, which this case falls into the latter.

**Comment by onoderat** [comment]
Thanks for the notice. Is there a rough idea for when this would be implemented? 

Some of my colleague run a [Runge-kutta SDE solver](https://en.wikipedia.org/wiki/Runge–Kutta_method_(SDE)) in python. I could possibly port this over to DifferentialEquations.jl if you think this would be a good fit for your repo.

**Comment by ChrisRackauckas** [comment]
The methods on that page aren't the high order (just 1.0) scheme. That's the RKMil method which does up to commutative noise so RKMilCommute will do that.

I haven't specialized on scalar noise simply because I haven't seen an application yet. And general non diagonal noise needs the full Wilkerson of course.

**Comment by ChrisRackauckas** [comment]
I should note that the Wikipedia article is slightly off. The scheme that is shown there is only written for scalar noise. That would work in this case, but not most cases. If dW is a vector, then you can do something similar when `b` is diagonal, and that is `RKMil`. If `dW` is a vector and `b` satisfies the commutivity property, then you have to add a bunch of steps to make it `RKMilCommute`. If `b` doesn't satisfy the commutivity property. then it's non-diagonal noise you have to compute the Levy area and take proportionally to `dt` more random numbers and compute a big summation to do so. [See this reference for more information on that](http://www.sciencedirect.com/science/article/pii/S0377042706004195).

So from that you can tell that since scalar noise and diagonal noise algorithms have the same noise complexity to achieve the correct strong order, the diagonal noise algorithms just need to be extended to understand how to use `dW` when it's a scalar instead of a `Vector`. Since it seems like that is being requested now, I'll see if I can get that done on a plane ride I'm taking next week.

**Comment by ChrisRackauckas** [comment]
This particular issue was handled since the higher order methods now allow scalar noise:

http://docs.juliadiffeq.org/latest/tutorials/sde_example.html#Example-3:-Systems-of-SDEs-with-Scalar-Noise-1

However, the more general cases of non-diagonal noise require completely different methods as described above.  The discussion is moved to https://github.com/JuliaDiffEq/StochasticDiffEq.jl/issues/44 since that's a very specialized topic specifically for that package.
