### ISSUE TITLE
More sophisticated save options

### ISSUE THREAD

**Issue by ranocha** [JuliaDiffEq/DifferentialEquations.jl#202]
It would be very nice to have two different save options

- Saving the solution at specified time points as possible using `saveat`, `tstops`, `save_idxs` now.
- Saving some processed quantities `saveval(t, u, f)` at another set of specified time points.

The processed quantities could be something like total energy, entropy, errors, etc. I have semidiscretisation of PDEs in mind, using many degrees of freedom in total (i.e. `u` is a large array) and I'm interested in the complete solution only at very few time points. However, I'm interested in (some scalar) derived quantities and their time evolution.

**Comment by ChrisRackauckas** [comment]
I wonder if a `DiscreteCallback` is the right solution for this. It would give a lot more control than the saving options ever could. The issue is that the dense output can only ever be really for the system itself. `save_idxs` make it so the interpolation does less work. Allowing one to choose a function call to do after the interpolation would be very breaking since the interpolation needs to use `sol.u` itself, so only intermediate interpolations (`saveat`) could hope to work. Even then, putting a function call in there to intercept right after the interpolation only would work in the case where you keep the array of the same type, so it's still not all that flexible. So it seems like it would be really breaking to try to go this route. Of course, it's definitely possible to setup every interpolation to have a function call to `saveval` as well, but it would take quite a bit of code churn and lots of safety checks would need to be added.

On the other hand, we can add a simple callback to the callback library `DiffEqCallbacks.jl` which could handle this kind of stuff. The idea would be the following. Allow it to take in `saveat`, `save_everystep`, and `saveval`. It would also take in a `sol_array`, which the user sets up as an array that it can save into (so they can build their own type for the saving if they want). In this case, we could do `saveval(t,u,integrator)`, the `t` and the `u` explicit because of the `saveat` doing the interpolation. Additionally `save_idxs` could be provided which would just change how much of `u` is interpolated (mostly for efficiency here).

What it would look like is this:

```julia
saveval(t,u,integrator) = length(u)
save_array = Vector{Int}()
cb = SavingCallback(saveval,save_array ,saveat=0:0.1:100,save_everystep=false)
sol = solve(prob,alg,save_everystep=false,callback=cb) # all saving is in the callback
cb.save_array # retrieve what you saved
```

The implementation could pull heavily from `savevalues!` in OrdinaryDiffEq.jl. The advantage here is that this is much easier to implement, the user can save to type they want, has full control, and we do not need to worry about breaking anything. The disadvantage of course is that this is slightly out of the way and not as easy as just one more argument to `solve`, but at least as a temporary workaround this could do well.

**Comment by ranocha** [comment]
Shall we close this now? I've updated the documentation of the callback library (https://github.com/JuliaDiffEq/DiffEqDocs.jl/pull/52).

**Comment by ChrisRackauckas** [comment]
Yup. Nice job!
