### ISSUE TITLE
Symplectic integrators and Fully Implicit Runge-Kutta Methods

### ISSUE THREAD

**Issue by mikelehu** [JuliaDiffEq/DifferentialEquations.jl#213]
We  have implemented symplectic integrators and fully Implicit Runge-Kutta Methods in language C :
     Fixed-Point iteration: https://github.com/mikelehu/IRK-FixedPoint
     Newton simplified iteration:  https://github.com/mikelehu/IRK-Newton

I am interesting  on learning about the package for solving differential equations in Julia. 
How can I study Julia implementations of symplectic and IRK methods?

Regards,
Mikel

**Comment by ChrisRackauckas** [comment]
The symplectic integrators from 

http://docs.juliadiffeq.org/latest/solvers/dynamical_solve.html#Symplectic-Integrators-1

are explicit, and you can see their internal steps written out here:

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/integrators/symplectic_integrators.jl

They are written that way so that way instead of loops so that they generate efficient GPU kernels. 

As for implicit symplectic integrators, we only have one simple one for now. Again, you can read it by seeing its `perform_step!` method, since the rest of the step handling is the same between all methods:

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/integrators/sdirk_integrators.jl#L336-L445

It's written out in a way that uses quasi-Newton steps with the same failure detection detailed in Hairer II.

Note that we do not currently have fully-implicit RK methods like Gauss methods. Our only fully implicit RK method is `radau` which is a direct wrapper of Hairer's library, but it's planned in the near future to tackle them. The difficult part of course is making them efficient by implementing them under the right transformation, like in the paper you detail which is actually just a version of Hairer's method (without citation...).

**Comment by mikelehu** [comment]
I have planned to study your implementations details next weeks.  
If I can help you on  anything , please contact me.

I sincerely thank you. 
Mikel

**Comment by ChrisRackauckas** [comment]
I don't think there's anything actionable here so I'm going to close this, but feel free to contact us at any time.
