### ISSUE TITLE
My ODEProblem gets passed ForwardDiff.Dual arguments instead of Float64

### ISSUE THREAD

**Issue by niclasmattsson** [JuliaDiffEq/DifferentialEquations.jl#229]
I'm trying to learn from my mistakes, so this time I'll open an issue here instead of [posting at Discourse](https://discourse.julialang.org/t/need-help-interpreting-an-error-message-differentialequations-jl-and-ida/7986).

My climate model is a DAE system. It passes around its state in a mutable struct, with fields declared as `::Float64`, `::Dict{Symbol,Float64}` and `::Vector{Float64}`. Everything works perfectly when I solve it as a `DAEProblem` using IDA. But when I try to solve it as an `ODEProblem` with a singular mass matrix, I get a ton of errors because the main function `f!(t,u,du)` gets passed arguments of type `ForwardDiff.Dual` instead of `Float64`.

The first error I get depends on which solver I use. Sometimes the model chokes at the point where I construct the main state struct:
```
ERROR: MethodError: Cannot `convert` an object of type ForwardDiff.Dual{ForwardDiff.Tag{DiffEqDiffTools.UJacobianWrapper{TempmodelDE.##37#42{Dict{Symbol,Array{Float64,1}},TempmodelDE.ClimateParams},Float64},Float64},Float64,10} to an object of type Float64
This may have arisen from a call to the constructor Float64(...), since type constructors fall back to convert methods.
```
And sometimes it borks on my helper functions that use the time parameter `t`:
```
ERROR: MethodError: no method matching iyear(::ForwardDiff.Dual{ForwardDiff.Tag{DiffEqDiffTools.TimeGradientWrapper{TempmodelDE.##37#42{Dict{Symbol,Array{Float64,1}},TempmodelDE.ClimateParams},Array{Float64,1}},Float64},Float64,1}, ::Base.#floor)
Closest candidates are:
  iyear(::Float64, ::Function) at c:\Stuff\Julia\Modules\TempmodelDE\src\TempmodelDE.jl:15
```

I can fix the problem myself by defining all model variables as `Real` instead of `Float64`. It works but kills performance, so I doubt this is intended. I could also convert the `u` and `du` vectors to and from `Float64` on both ends of `f!(t,u,du)` but this is also painful.

I doubt it's relevant but just in case: the DAE and ODE problems are constructed using anonymous functions in order to pass extra parameters, like this:

```
prob = DAEProblem(
    (t,u,du,out) -> f!(t,u,du,out, annualemissions, p),
    u0, du0, tspan, differential_vars=differential_vars
)
solve(prob, IDA(), saveat=1.0, abstol=abstol, reltol=reltol)

ld = length(differential_vars)
M = eye(Int, ld) .* differential_vars
prob = ODEProblem(
    (t,u,du) -> f!(t,u,zeros(ld),du, annualemissions, p),
    u0, tspan, mass_matrix=M
)
solve(prob, Rodas4(), saveat=1.0, abstol=abstol, reltol=reltol)
```

**Comment by ChrisRackauckas** [comment]
Yes, many of the OrdinaryDiffEq.jl methods use autodifferentiation by default which requires compatibility with `Dual` numbers. You don't need set all of your arrays to `Real`, you can instead use a cache with both a proper Dual and a Float64 and have it pick using dispatch, and that will infer. I will say that's not trivial to setup and I should probably do a blog post on it. 

The options for differentiation are explained here:

http://docs.juliadiffeq.org/latest/solvers/ode_solve.html#Extra-Options-1

To turn off `autodiff` in the solver, just pass `autodiff=false`. Example: `Rodas4(autodiff=false)` and it will use numerical differentiation which is a bit slower and less accurate but more compatible with black-box functions.

For reference, you can create a usable cache via:

```julia
struct MyTag end

immutable DiffCache{T<:AbstractArray, S<:AbstractArray}
    du::T
    dual_du::S
end

Base.@pure function DiffCache{chunk_size}(T, size, ::Type{Val{chunk_size}})
    DiffCache(zeros(T, size...), zeros(Dual{typeof(ForwardDiff.Tag(MyTag (),T)),T,chunk_size}, size...))
end

Base.@pure DiffCache(u::AbstractArray) = DiffCache(eltype(u),size(u),Val{ForwardDiff.pickchunksize(length(u))})
Base.@pure DiffCache(u::AbstractArray,nlsolve) = DiffCache(eltype(u),size(u),Val{get_chunksize(nlsolve)})
Base.@pure DiffCache{CS}(u::AbstractArray,T::Type{Val{CS}}) = DiffCache(eltype(u),size(u),T)

get_cache{T<:Dual}(dc::DiffCache, ::Type{T}) = dc.dual_du
get_cache(dc::DiffCache, T) = dc.du
```

To use this, you now create a `DiffCache`:

```julia
cache = DiffCache{chunk_size}(T, size, ::Type{Val{chunk_size}})
```

where `T` is the original element type (`Float64` in your case). Then in your function, you access it like:

```julia
function f(t,u,du)
  my_cache = get_cache(u)
end
```

and that will be a cache of Dual numbers when `u` is Dual and it will be a cache of Float64s when `u` is Float64s, and it will infer because it's just using dispatch on the type-specialization.

I can make this into a small package to make it easier and document it. But in the end, the change to autodiff via Cassette.jl will make this unnecessary since then it won't need Dual numbers.

**Comment by niclasmattsson** [comment]
I understand, thank you. Guess I was wrong to post an issue after all. :) That cache implementation was really cool but I think I need to grok it more before I use it in production code. I'll try running with autodiff off for now and update the model sometime in the future when your blog inspires me to.

BTW, I had to look up was Cassette was and my mind is suitably blown. I'm hitting play on [the JuliaCon video](https://www.youtube.com/watch?v=SXJ0ZfawzxA) right about ... now.

**Comment by ChrisRackauckas** [comment]
Alright. Just an FYI the numerical gradient calculations without autodiff is a little slow right now. That plus the inaccuracy of numerical diff in general makes me think that `Rodas4` might not do well here (since high order Rosenbrock methods need accurate Jacobians/gradients) so `IDA` will likely work out better (at least for now). The latest release of Sundials now makes it compatible with a large amount of diffeq extras like callbacks, so unless you're doing something fancy it should satisfy, but let me know if it doesn't.

I'm closing this because there doesn't seem to be anything actionable left (other than maybe a blog post).

**Comment by ChrisRackauckas** [comment]
The solution to this is now in the docs. 

https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues?q=is%3Aissue+is%3Aclosed
