### ISSUE TITLE
Invalid Tag object when using stiff solver with ODELocalSensitivityProblem

### ISSUE THREAD

**Issue by rlecover007** [JuliaDiffEq/DifferentialEquations.jl#238]
If a jacobian is not supplied, trying to use a stiff solver with an ODELocalSensitivityProblem results in:

ERROR: Invalid Tag object:
  Expected ForwardDiff.Tag{DiffEqDiffTools.UJacobianWrapper{DiffEqBase.ParameterizedFunction{true,##1#2,Array{Float64,1}},Float64},ForwardDiff.Dual{ForwardDiff.Tag{DiffEqDiffTools.UJacobianWrapper{DiffEqSensitivity.ODELocalSensitvityFunction{DiffEqBase.ParameterizedFunction{true,##1#2,Array{Float64,1}},DiffEqDiffTools.UJacobianWrapper{DiffEqBase.ParameterizedFunction{true,##1#2,Array{Float64,1}},Float64},DiffEqDiffTools.ParamJacobianWrapper{DiffEqBase.ParameterizedFunction{true,##1#2,Array{Float64,1}},Float64,Array{Float64,1}},ForwardDiff.JacobianConfig{ForwardDiff.Tag{DiffEqDiffTools.UJacobianWrapper{DiffEqBase.ParameterizedFunction{true,##1#2,Array{Float64,1}},Float64},Float64},Float64,2,Tuple{Array{ForwardDiff.Dual{ForwardDiff.Tag{DiffEqDiffTools.UJacobianWrapper{DiffEqBase.ParameterizedFunction{true,##1#2,Array{Float64,1}},Float64},Float64},Float64,2},1},Array{ForwardDiff.Dual{ForwardDiff.Tag{DiffEqDiffTools.UJacobianWrapper{DiffEqBase.ParameterizedFunction{true,##1#2,Array{Float64,1}},Float64},Float64},Float64,2},1}}},ForwardDiff.JacobianConfig{ForwardDiff.Tag{DiffEqDiffTools.ParamJacobianWrapper{DiffEqBase.ParameterizedFunction{true,##1#2,Array{Float64,1}},Float64,Array{Float64,1}},Float64},Float64,2,Tuple{Array{ForwardDiff.Dual{ForwardDiff.Tag{DiffEqDiffTools.ParamJacobianWrapper{DiffEqBase.ParameterizedFunction{true,##1#2,Array{Float64,1}},Float64,Array{Float64,1}},Float64},Float64,2},1},Array{ForwardDiff.Dual{ForwardDiff.Tag{DiffEqDiffTools.ParamJacobianWrapper{DiffEqBase.ParameterizedFunction{true,##1#2,Array{Float64,1}},Float64,Array{Float64,1}},Float64},Float64,2},1}}},Array{Float64,1},DiffEqSensitivity.SensitivityAlg{0,true,DataType},Array{Float64,1},Float64},Float64},Float64},Float64,6}},
  Observed ForwardDiff.Tag{DiffEqDiffTools.UJacobianWrapper{DiffEqBase.ParameterizedFunction{true,##1#2,Array{Float64,1}},Float64},Float64}.

MNWE
```
using DifferentialEquations
using Plots

pf_func = function (t,u,p,du)
  du[1] = p[1] * u[1] - p[2] * u[1]*u[2]
  du[2] = -3.0 * u[2] + u[1]*u[2]
end

pf = ParameterizedFunction(pf_func,[1.5,1.0])
@show typeof(pf)
prob = ODELocalSensitivityProblem(pf, [1.0; 1.0], (0.0, 10.0))

sol = solve(prob,Kvaerno5())
x,dp = extract_local_sensitivities(sol)
@show size(dp)
@show size(dp[1])
@show size(sol.t)
plot(sol.t, dp[1]')
```

**Comment by ChrisRackauckas** [comment]
I edited the post to fix the MWE. The problem is autodifferentiation with cache variables. The FAQ discusses this:

http://docs.juliadiffeq.org/latest/basics/faq.html#I-get-Dual-number-errors-when-I-solve-my-ODE-with-Rosenbrock-or-SDIRK-methods...?-1

but we didn't setup our sensitivity equation methods to be autodiff-aware in that sense. So a temporary fix is `sol = solve(prob,Kvaerno5(autodiff=false))` or as you say if the Jacobian is provided it will work as well. But the way to fix it is exactly like that FAQ, we just need to do it on our side.

The more general fix to this problem is supposedly going to be via Cassette.jl and Capstan.jl where it will no longer require dispatch on Dual numbers. Hopefully that comes sooner rather than later!

**Comment by ChrisRackauckas** [comment]
This has been addressed.
