### ISSUE TITLE
Suggestion for version 5: move `tspan` to integrators, keep only t0

### ISSUE THREAD

**Issue by Datseris** [JuliaDiffEq/DifferentialEquations.jl#249]
Here is a crazy suggestion for DifferentialEquations version 5, in case you want to consider it!

I always felt uncomfortable that `tspan` is a mandatory part of `DEProblem`. From the solution/uniqueness perspective, the vector field and an initial condition are enough. In the case of non-autonomous DiffEq, you also need t0. Then you add parameter container, callbacks and mass matrix.

I propose to remove `tspan` from `DEProblem` and instead have `t0` for `Problem` and `tfinal` for the `DEIntegrator`. This will also finally allow a default `t0= 0.0` for all `Problem` constructors which is true for like 99% percent of the time.

`tfinal` can/should be a mandatory *argument*, like `init(prob, alg, tfnal; kwargs...)`.

This also makes it more comfortable and intuitive for libraries such as `ChaosTools` that do not care about `tspan` and use `step` instead.

(yes I am weeeell aware that this probably won't happen as it will break everything, it is a lot of work *and* doesn't change much, but still it is nice to voice this opinion somewhere. this issue is the where)

**Comment by ChrisRackauckas** [comment]
Yes, it's a crazy suggestion. 

I'm against it not because it would break everything (this is simple to deprecate anyways, so it would throw a warning and be much nicer than the function syntax change). I'm against it because I don't think it would be helpful.

First of all, in any case you want to solve an ODE numerically, we need the time span. We can't do anything without it. So this would just be moving it from the problem definition to the solve command. Uniqueness of a solution can depend on the direction of time too, so a mathematical argument doesn't follow there. Also, there are a lot of cases where `t0 != 0.0`, so I don't think that is true close to 99% of the time for general use cases. 

To be fair, there was a time in pre-1.0 DiffEq that it was like this. One reason we switch was so that way we'd have better control over the type for time (allowing compatibility with units). But it was also just weird that domain was specified separately from the problem. The domain becomes a bigger deal with PDEs where the domain isn't just time but also space. So then you start getting non-standard `init` and `solve` calls requiring different arguments for different PDEs, instead of describing everything off of the `Problem` type constructor. It was getting really confusing which is why we moved to describing domains in the problem. The result really isn't much different for ODEs, but it scales to other problems in a much more straight-forward way.

**Comment by Datseris** [comment]
Fair enough. Of course when writing this I did not consider PDEs, where the argument is very strong there. 

I wasn't really going to argue much about it. AFter your answer seems even more valid to use `tspan`.
