### ISSUE TITLE
Saveat with save_positions=(true,true)

### ISSUE THREAD

**Issue by ivborissov** [JuliaDiffEq/DifferentialEquations.jl#288]
If a time point is included both in `saveat` and Callback `tstops` with default `save_positions=(true,true)` it is saved 3 times. What is a good solution to have only 2 saved time points in such cases? We can use `save_positions=(false,true)` but then we will loose those `tstops` which are not in `saveat`

**Comment by ChrisRackauckas** [comment]
These are all changed on master branches to exclude the first save if `integrator.t` matches the current last saved time point.

**Comment by ivborissov** [comment]
Chris, thanks.

I've checked out `OrdinaryDiffEq` but in this example I have still 3 time points `t=10.`

```
using OrdinaryDiffEq, DiffEqCallbacks, RecursiveArrayTools

p_func = function(du, u, p, t)
    v1 = u[1]*p[1]*p[2]
    du[1] = -v1/p[2]
    du[2] = v1/p[2]
end

condition = function(u, t, integrator)
    isequal(t, 10.0)
end

affect = function(integrator)
#    saveAddComponents(integrator)
    integrator.u[1] = 10.
    integrator.u[2] = 0.
#    saveAddComponents(integrator)
end

cb = DiscreteCallback(condition, affect, save_positions =(true,true))

prob = ODEProblem(p_func, [10.0,0.0], (0.0,100.), [1.5, 1.0])
@time sol = solve(prob, Tsit5(), tstops = [10.0], saveat=1.0, callback=cb)
```

**Comment by ChrisRackauckas** [comment]
Oh, this issue is actually very deep and harder to solve than I thought. Notes for future attempts:

The callback is doing saveat because saveat is before the forced and `save_everystep` save. But `saveat` will already state the point that is forced. Save forcing is required for the pre-callback save call since otherwise it wouldn't work if not save_everystep. But that force then makes the pre-callback save double. However, we don't want to do a time check there, since the post-callback save is a case where we want to force the save to happen at the same time point. So some how we need to make the first force different than the second.

**Comment by ChrisRackauckas** [comment]
@YingboMa solved this.

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/505
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/506
