### ISSUE TITLE
GPU Parallel Monte Carlo

### ISSUE THREAD

**Issue by agerlach** [JuliaDiffEq/DifferentialEquations.jl#308]
I have a need to run some large scale Monte Carlo simulations w/ random initial conditions and parameters for small scale ODEs (<10 states). Is it possible to do parallel Monte Carlo simulation using the GPU? 

I see that you support GPU, but all the examples look like the parallelization happens within the EOMs and you need very large systems vs. each GPU thread solving the EOMs independently on different data.

I have implemented large scale Monte Carlo simulations w/ VexCL and Boost ODEINT but event detection is essentially non existent. I will admit that I am a Julia novice, but my interest in learning more is primarily driven by this awesome library. 

Thanks.

**Comment by agerlach** [comment]
Bummer. Thanks for the info though. Other than this one "killer feature" I would say that DifferentialEquations.jl is the tool I have been looking for for years. Hopefully, some of my experience using VexCL + ODEINT will be of some help.

> Until we have that, yes our GPU parallelism is at the vector level. If I'm not mistaken, that's the same as VexCL and ODEINT strategy which GPU-parallelize through GPU-based vectors?

Yes and no. VexCL certainly does parallelism at the vector level, but I think the vectors are defined differently. DifferentialEquations.jl is parallelizing across the state vector. VexCL is parallelizing across an ensemble vector. For example, lets say you want to run `n` Monte Carlo simulations of a system with `m` states. In VexCL you first create `n` arrays of length `m` (or vector of vectors) and then initialize them with random initial conditions. The `n` arrays (1 for each state) get passed as arguments to the resulting kernel and then `m` gpu threads run, operating only on a given idx into the `m` length arrays. 

For my application the dynamics are quite slow, so I've been able to get away with a fixed time-step RK4 integrator...for now.  It does sound like adaptive time stepping should work with VexCL, you just need to keep track of an array of time steps, one for each thread.

Each kernel call simply does a single step update for the whole ensemble. This gets wrapped in a host `for` loop until the final time is reached. Event detection is handled pretty crudely by running a separate kernel after each step to check if the desired 0 crossing occurs. If so, linear interpolation is performed between the current and prior states. I haven't implemented time step refinement because, to this point, this has been sufficient for my application.

This was all done using VexCL's [symbolic types](http://vexcl.readthedocs.io/en/latest/symbolic.html). For more details on how I generated the kernels for my problem see[ VexCL Issue#202 ](https://github.com/ddemidov/vexcl/issues/202#issuecomment-216244202). I also discussed event detecction in [VexCL Issue#203](https://github.com/ddemidov/vexcl/issues/203)

**Comment by ChrisRackauckas** [comment]
I see. Yes, you can do the VexCL version in DiffEq by using a GPUArray of static arrays and then broadcast calling your derivative kernel on this GPUArray{SArray}. But that will never scale to event handling since then the timesteps are global, i.e. all integrations are advancing with the same `dt`, so having a different event on each one will slow it down enormously... so I wouldn't even try this approach with events.

But I have a solution in mind. It will need Julia v1.0 and since that will be out in <2 months, let's wait for then. Ping me after Julia v1.0 comes out and I'll get an adaptive integrator that auto-compiles to the GPU with event handling.

**Comment by agerlach** [comment]
@ChrisRackauckas Awesome! Thanks for all your great work.

**Comment by titusfranz** [comment]
@ChrisRackauckas Thank you for your amazing package, I'm using it already heavily for my simulations. Julia 1.0 is now out, are there already news about the adaptive intergrator that auto-compiles to the GPU with event handling?

Thanks in advance.

**Comment by ChrisRackauckas** [comment]
What I have planned here for the short term won't do event handling. Doing event handling would require getting the of OrdinaryDiffEq.jl to compile to the GPU which needs Cassette.jl to be released (so we can overdub the array allocations)

**Comment by ChrisRackauckas** [comment]
Found some precedence: https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=5710898

**Comment by agerlach** [comment]
@ChrisRackauckas Good find. I actually stumbled on that paper a few years ago when I started using VexCL+ODEINT but completely forgot about it. FYI, the author has source code here: [LibBi](https://github.com/lawmurray/LibBi/tree/master/share/src/bi/cuda/ode)

My apologies for my radio silence on this. I somehow missed your previous posts. What do you have in mind for your short-term plan?

**Comment by ChrisRackauckas** [comment]
My short term plan is a direct implementation of Tsit5 into SimpleDiffEq.jl using only static arrays and only allowing `saveat` so it can interpolate to a fixed size output array. That should be CUDANative-able. From there we can do Vern9 and a low storage method. That should be a good setup while we play with trying to get full integrators to compile. These will not have the integrator interface because the difficult part is precisely the `integrator` `mutable struct`'s interaction with CUDANative, but these should be able to handle ODEs without events. Then a simple Rosenbrock23 and RKN methods handle the stiff side, and that's a decent GPU offering. 

@YingboMa could probably help with getting some of it done. We have applications and funders who are interested so that will drive it pretty soon.

**Comment by ChrisRackauckas** [comment]
The SimpleTsit5 and SimpleATsit5 implementations should be GPU-compatible given discussions with the CUDANative.jl devs. The PR which added the adaptive one can be found here:

https://github.com/JuliaDiffEq/SimpleDiffEq.jl/pull/10

Essentially that `solve` call can just be CUDANative compiled to a kernel since all of the mutables have a lifespan within the solve call.

**Comment by ChrisRackauckas** [comment]
This is now being handled at https://github.com/JuliaDiffEq/DiffEqGPU.jl
