### ISSUE TITLE
Error while determining the derivative at end points

### ISSUE THREAD

**Issue by mstiitb** [JuliaDiffEq/DifferentialEquations.jl#311]
I am new to Julia and so please pardon if the following is too trivial. I am solving an ODE and I am interested in the derivative and second derivative of the solution. In my problem, I need the derivatives as they go into the RHS of a second ODE. There is one way coupling between the two sets of ODEs.

I tried using Calculus.derivative(u,x) etc in the second ODE, where x is a vector and u is the solution from the first ODE. I get the error:"Solution interpolation cannot extrapolate before the first timepoint. Either start solving earlier or use the local extrapolation from the integrator interface.". 

I am guessing that the derivative is being calculated at the first point using central differences and hence the problem (we do not know the solution for x<x0 for x-range from x0 to xf). Is there a way of extrapolating the derivative calculated at points close to x0 (and a similar procedure at the end point) while the derivative at rest of the points are determined using central differences? The error message is suggesting a way using the "integrator interface" but I do not understand this very well.

I just checked with a similar function in MATLAB and it appears that the "gradient" function there calculates the central difference numerical derivative, except at the edges or ends, where it calculates a one-sided derivative. Is this an issue here?

**Comment by ChrisRackauckas** [comment]
Numerical differentiation like this is prone to errors. Instead, we have a high order derivative approximation via analytical calculations on the interpolating polynomial. See http://docs.juliadiffeq.org/latest/basics/solution.html#Interpolations-1 . 

```julia
sol(t,Val{i})
```

Change `i` to the derivative that you want. Not all methods have all of the derivatives implemented, but for example `Vern9` has 4 derivatives you can use and so does `Tsit5` IIRC. These formulas are not prone to the numerical issues of numerical differentiation and should be much more accurate.

Additionally, you can make use of ForwardDiff.jl to calculate derivatives without numerical differentiation.  This uses Dual numbers instead of epsilon changes and thus does not need to extrapolate to do so.

You are indeed correct about the reason why numerical differentiation is throwing an error, and no you cannot extrapolate the derivative before x0 because the equations behavior in that area is undefined. If you wanted to make numerical differentiation work in this case, you would have to manually change to forward differencing when you get to small values (not too difficult if you just write the loop). However, I would highly suggest these other routes instead.

**Comment by mstiitb** [comment]
Chris just informed me that there is an elegant way of doing this:
sol(t,Val{i})
Details are on: http://docs.juliadiffeq.org/latest/basics/solution.html#Interpolations-1

**Comment by mstiitb** [comment]
Thank you very much, Chris. It works !

I have seen that webpage so many times but I still missed it. I have closed the issue.

Regards
Mahesh
