### ISSUE TITLE
Problem with Event Handling

### ISSUE THREAD

**Issue by ChrisNabold** [JuliaDiffEq/DifferentialEquations.jl#364]
I tried to solve the following problem 
[Juliatest.txt](https://github.com/JuliaDiffEq/DifferentialEquations.jl/files/2453159/Juliatest.txt)

question why is sol[1,end] not equal to 6.37814 as defined in condition(u,t,integrator).
The function us is almost linear around time=1000 and therefore a linear interpolation/extrapolation would give a satisfactory solution.
A manual interpolation with dtmax=100 would result in a better solution

**Comment by ChrisRackauckas** [comment]
`condition(u,t,integrator) = u[1]>6.37814e6` doesn't make sense in a `ContinuousCallback`. The function should be a continuous rootfinding function, like `condition(u,t,integrator) = u[1]-6.37814e6`. Otherwise any value for which it's false is a valid stopping point (since then u[1]>6.37814e6 = 0 which is a root of the function).

**Comment by ChrisNabold** [comment]
Dear Christopher

 

Thank you for your help.
