### ISSUE TITLE
Solve Integro-differential equation?

### ISSUE THREAD

**Issue by mleprovost** [JuliaDiffEq/DifferentialEquations.jl#383]
Hello, 

Is there a way to solve integro-differential equations without differentiating the equations to get rid of the integrals. I mean solve equations of this type with history terms: 
![codecogseqn 3](https://user-images.githubusercontent.com/38221506/48505164-41b52c00-e7fb-11e8-875e-84f1b932dcd3.gif)

**Comment by ChrisRackauckas** [comment]
Yes, you can use the delay differential equation solver. It has a derivative function `f(du,u,h,p,t)` where `h(p,t)` is a function of past time points. Using this you can write a discrete approximation to the integral or use QuadGK.jl. With quadgk, I would suggest using `MethodOfSteps(RK4())` for the residual error control and just not specifying the delays because of the adaptivity. With a finite discretization of the integral you'd get a constant delay DDE which can use any of the methods quite effectively.

**Comment by mleprovost** [comment]
Thank you, I will try that

**Comment by detrin** [comment]
I am trying to implement solver for Quantum Master Equation in OpenQuantumSystems.jl with adaptive stepsize using the method mentioned above. I found out that `MethodOfSteps(Vern7()))` is much quicker for smaller precision (rtol=atol=1e-6) and for higher precision  (rtol=atol=1e-10) `OrdinaryDiffEq.Tsit5())` works pretty well.
