### ISSUE TITLE
Issue with PDMP - DifferentialEquations and PDMP

### ISSUE THREAD

**Issue by rveltz** [JuliaDiffEq/DifferentialEquations.jl#387]
Hi,

In the following example, Forwardiff called from `Rosenbrock23()` fails. I spent quite some time to debug it. Please note that Forwardiff works with `PDMP.jl`. An example is the [here](https://github.com/rveltz/PDMP.jl/blob/master/examples/tcp.jl).

Hence, I am a bit stuck here. Maybe you guys from DiffEq have an idea.

thank you for your help,

```julia
using PDMP, LinearAlgebra, Random, DifferentialEquations

function F_fd!(ẋ, xc, xd, t, parms)
    # vector field used for the continuous variable
    if mod(xd[1],2)==0
        ẋ[1] = 1 + xd[1]
    else
        ẋ[1] = -1
    end
    nothing
end

rate_tcp(x) = 1/x

function R_fd!(rate, xc, xd, t, parms, sum_rate::Bool, glu = 1.2)
    # Glu = xc[1] * glu * 1.213123
    rate[1] = rate_tcp(xc[1]) * xd[1]
    rate[2] = 0.0
    if sum_rate==false
        return 0., 0.
    else
        return sum(rate), 0.
    end
end

xc0 = [ 1.0 ]
xd0 = [1, 1]

nu_fd = [[1 0];[0 -1]]
parms = [0.0]

# works:
res =  @time PDMP.pdmp!(xc0, xd0, F_fd!, R_fd!, nu_fd, parms, 0.0, 1.0, n_jumps = 3,   ode = Tsit5())
# fail because of autodiff
res =  @time PDMP.pdmp!(xc0, xd0, F_fd!, R_fd!, nu_fd, parms, 0.0, 1.0, n_jumps = 3,   ode = Rosenbrock23())
```

**Comment by ChrisRackauckas** [comment]
In PDMP you need to make `rate` a dual cache so that way it can hold Dual numbers. See http://docs.juliadiffeq.org/latest/basics/faq.html#I-get-Dual-number-errors-when-I-solve-my-ODE-with-Rosenbrock-or-SDIRK-methods...?-1 . As it stands, the `rate` function you create is only for Float64, so then when `xd` is dual during differentiation it causes an issue. You can get around that by disabling it ( `Rosenbrock23(autodiff=false)`), not using mutation for `rate`, having a dual cache, or using a different form of differentiation for the Jacobian.

**Comment by rveltz** [comment]
What do you mean by "not using mutation for `rate`"?

**Comment by ChrisRackauckas** [comment]
Allocating `rate` instead of mutating the buffer. Basically, either the buffer needs to be a dual buffer to handle Dual number inputs, or it needs to be allocated each time to handle the type changes. The former is more performant and the latter is easier. But to autodiff the derivative function, one of those choices need to be made.
