### ISSUE TITLE
Root finding doesn't work properly when condition uses DEDataArray fields

### ISSUE THREAD

**Issue by BenWhetton** [JuliaDiffEq/DifferentialEquations.jl#391]
I have come across a problem when trying to trigger events with conditions which use data from a DEDataArray.
In my scenario, I have a variable which is calculated using a lookup table every iteration and the callback condition uses this value. It seems that the calculated value of the callback condition (from `zero_func` in `find_callback_time` in `callbacks.jl` doesn't change at all when it depends on DEDataArray fields.

I don't know where in the codebase the DEDataArray fields are calculated (and I find it a bit tricky to navigate coming from languages with fully-featured IDEs) so that's where my debugging has got stuck.

Here's some code which reproduces the problem. I'm happy to continue investigating if someone who knows the codebase can point me in the right direction.

```julia
using DifferentialEquations

mutable struct MyDataType{T} <: DEDataVector{T}
  x::Array{T,1}
  data::T
end

function my_model(du, u, p, t)
     u.data = u[1]/2  # In my application, this is a lookup table call
     du[1] = 100*pi/3
end

function wrapCondition(u,t,integrator)
     # return u[1]/2 - pi/4  # this works
     return u.data - pi/4  # but this doesn't work!
end

function wrapAffect!(integrator)
     print(integrator.u[1])
     integrator.u[1] = mod(integrator.u[1], pi/4)
     print("wrapping!")
end

function simulate()
     save_positions = (true,true)
     wrapCb = ContinuousCallback(wrapCondition, wrapAffect!, nothing; save_positions=save_positions, rootfind=true)

     u0 = MyDataType([0.0], 0.0)
     prob = ODEProblem(my_model, u0, (0.0, 0.05))
     sol = solve(prob, Tsit5(); callback = wrapCb)
     return sol
end

sol = simulate()
```

**Comment by isentropic** [comment]
Maybe you should use
```
function affect!(integrator)
  for c in full_cache(integrator)
    c.f1 = 1.5
  end
end
```
that is to modify the whole stack, not just a current value, just as instructed in the docs

**Comment by ChrisRackauckas** [comment]
Well the true answer is that the values in the DEDataArray are piecewise constant by definition since they do not have an associated derivative term (and this is then how the interpolation treats them). So the stored value for `u.data` is a constant over that whole root finding which is why it fails. This isn't a bug but just part of the definition. `u[1]/2 - pi/4` is precisely what is meant to be done here, so I'm closing this.

But there is another idea hanging around here that is worth an issue. This idea of explicit algebraic variables, like `u[1]/2`, keeps coming up. I wonder if having a convenience for such a thing is worthwhile, and can be optimized moreso than a do-it-yourself fashion. That could be worth a good long discussion.

**Comment by BenWhetton** [comment]
Thanks for the replies.

@isentropic I did forget to update the whole stack! I'll make sure to do that in future.

@ChrisRackauckas I see. Is that currently documented anywhere? Explicit algebraic variables would be pretty great. I guess it depends whether you think it should be within the scope of this library or not.
In the mean-time, I think I have a better understanding of what is included in the framework and what I need to write myself now. Thanks.

**Comment by ChrisRackauckas** [comment]
http://docs.juliadiffeq.org/latest/features/diffeq_arrays.html#DEDataArrays-1

>The other fields are treated as "discrete variables".

**Comment by ChrisRackauckas** [comment]
Please feel free to PR the docs if that isn't clear.
