### ISSUE TITLE
Jacobians for SDEs

### ISSUE THREAD

**Issue by Krastanov** [JuliaDiffEq/DifferentialEquations.jl#402]
In the documentation I see that Jacobians (and much more) for SDEs are supported (http://docs.juliadiffeq.org/latest/features/performance_overloads.html#SDEFunction-1).

However, it seems like only the Jacobian of `f` can be specified (I assume `jac` means `jac of f`). Am I misreading this? In case I am not misreading, is the Jacobian of g simply never useful?

I assume it is the same with `tgrad` - this is simply the gradient of `f` wrt to `t`? `g` is not involved in this?

More generally, is there a table of which solvers are actually utilizing this additional functionality? I.e. are **all** solvers able to exploit **all** of `tgrad`, `jac`, `paramjac`, `invW` and `invW_t`?

**Comment by Krastanov** [comment]
Reading through this https://github.com/JuliaDiffEq/StochasticDiffEq.jl/blob/master/src/perform_step/sdirk.jl and this https://github.com/JuliaDiffEq/StochasticDiffEq.jl/blob/master/src/derivative_utils.jl my guess is that the only `g` related derivatives that can be supplied are `ggprime`. I guess this is obvious for people with knowledge of implicit SDE methods, but for amateur users like me it was not obvious.

**Comment by ChrisRackauckas** [comment]
Yes, and it's also changing. The methods until very recently were only drift-implicit, so only implicit in the `f` term. This is because the inverse of a standard normal has unbounded mean and thus cannot be proved to converge. Recently, new methods with full implicitness have been developed by truncating the stochastic terms appropriately. Additionally, new stochastic Rosenbrock methods would make use of tgrad, and such. So these choices will likely change as new algorithms get added, and there's some amount of pre-planning and others need to get added.

**Comment by Krastanov** [comment]
This is extremely exciting! The only complaint that I have is that a lot of this is not clear from the documentation currently (I frequently look through the source code to see which solver takes advantage of which derivative). I wish I could contribute to it so that it can be clarified, but I lack a lot of the understanding of **why** each solver is the way it is.

**Comment by ChrisRackauckas** [comment]
Yes, I'm reopening this as a documentation issue.

**Comment by ChrisRackauckas** [comment]
Clarified in the docs.
