### ISSUE TITLE
[question] syntax of in-place update

### ISSUE THREAD

**Issue by daviehh** [JuliaDiffEq/DifferentialEquations.jl#415]
Using the example in the documentation [here](http://docs.juliadiffeq.org/latest/tutorials/ode_example.html#Example-2:-Solving-Systems-of-Equations-1),

```
function lorenz(du,u,p,t)
 du[1] = 10.0*(u[2]-u[1])
 du[2] = u[1]*(28.0-u[3]) - u[2]
 du[3] = u[1]*u[2] - (8/3)*u[3]
end

u0 = [1.0;0.0;0.0]
tspan = (0.0,100.0)
prob = ODEProblem(lorenz,u0,tspan)
sol = solve(prob)
```
works as expected, however if we assign the value to du not through each element but by

```
function lorenz(du,u,p,t)
 du = [10.0*(u[2]-u[1]); u[1]*(28.0-u[3]) - u[2]; u[1]*u[2] - (8/3)*u[3]]
end

u0 = [1.0;0.0;0.0]
tspan = (0.0,100.0)
prob = ODEProblem(lorenz,u0,tspan)
sol = solve(prob) 
```
the result is just the initial u0. Feels like a silly mistake on my part but not sure exactly what went wrong here? I'm working with a complex matrix equation that makes assignment by index very cumbersome, but in matrix notation it's just terms like `du=u*a-b*u`, etc, where a,b,u,du are all matrices. Thanks!

btw, what's a good/acceptable place to ask such questions? Here as an issue or on stack exchange?

**Comment by ranocha** [comment]
In your example, you create a new matrix and assign it locally to `du`. If you want to modify `du` inplace, you should use `du[:] = ...` instead of `du = ..`, i.e.
```julia
function lorenz(du,u,p,t)
  du[:] = [10.0*(u[2]-u[1]); u[1]*(28.0-u[3]) - u[2]; u[1]*u[2] - (8/3)*u[3]]
end
```
If you use matrix products with small matrices, you might want to have a look at [StaticArrays.jl](https://github.com/JuliaArrays/StaticArrays.jl).

> btw, what's a good/acceptable place to ask such questions? Here as an issue or on stack exchange?

I would ask such questions on https://discourse.julialang.org.

**Comment by ChrisRackauckas** [comment]
Yes, the in-place syntax is for updating an already existing array. Any return value is ignored. This means that

```julia
function lorenz(du,u,p,t)
 du[1] = 10.0*(u[2]-u[1])
 du[2] = u[1]*(28.0-u[3]) - u[2]
 du[3] = u[1]*u[2] - (8/3)*u[3]
end
```

is best because it doesn't create any new arrays, while

```julia
function lorenz(du,u,p,t)
 du .= [10.0*(u[2]-u[1]); u[1]*(28.0-u[3]) - u[2]; u[1]*u[2] - (8/3)*u[3]]
end
```

works, or

```julia
function lorenz(du,u,p,t)
 du[:] = [10.0*(u[2]-u[1]); u[1]*(28.0-u[3]) - u[2]; u[1]*u[2] - (8/3)*u[3]]
end
```

works because these update the existing `du` array as well, but are not as performant because they create a temporary array.

If you want to be working by return values, you can use the out of place syntax, which is:

```julia
function lorenz(u,p,t)
  [10.0*(u[2]-u[1]); u[1]*(28.0-u[3]) - u[2]; u[1]*u[2] - (8/3)*u[3]]
end
```

Notice the different arguments. For a further discussion about optimizing your code in these different situations, consult [this tutorial notebook](https://nbviewer.jupyter.org/github/JuliaDiffEq/DiffEqTutorials.jl/blob/master/Introduction/OptimizingDiffEqCode.ipynb). 

>btw, what's a good/acceptable place to ask such questions? Here as an issue or on stack exchange?

The Slack/Gitter channels are a great way to talk something out and that might get a quicker response. The Discourse is a good place for questions with discussion. StackOverflow is nice because then the answerer gets points :), but not as many Julia users use it. The issue here are mainly focused on development discussions so the number of people actively following it is much less than the number of people who would know how to fix user errors, so I would recommend keeping this for bug reports. That said, I won't actively enforce that with an iron fist, but it would still be more beneficial to ask the wider community of users.
