### ISSUE TITLE
Missing/inconsistent Callbacks

### ISSUE THREAD

**Issue by vnvasquez** [JuliaDiffEq/DifferentialEquations.jl#456]
I am having a problem with inconsistent Callbacks in a control problem created using DiffEq.  This seems to be connected to interpolation. 
 
Below is a toy example replicating the issue. When the intervention is scheduled for t==2.0 and the total time span is (0.0, 4.0) all works as it should. However, when the intervention is scheduled for t == 3.0 for the same time span (0.0, 4.0), the Callback never occurs.  
 
```
mutable struct SimTypeM{T} <: DEDataMatrix{T}
    x::Array{T,2}
    f1::T
end
 
u0_array = [1.0 1.0;1.0 1.0]
u0 = SimTypeM(u0_array, 0.0)
 
function condition(u,t,integrator)
    t == 3.0
end
 
function affect!(integrator)
  for c in full_cache(integrator)
    c.f1 = 5
  end
end
 
save_positions = (true,true)
cb = DiscreteCallback(condition, affect!, save_positions=save_positions)
 
function gen(du, u, p, t)
    du[1,1] = u[2,1] - u[1,1]
    du[2,1] = u[1,1] - u.f1
    du[1,2] = u[2,2] - p[1]*u[1,2]
    du[2,2] = u[1,2] - p[2]*u.f1
    
    @show u.f1
end
 
prob = ODEProblem(gen, u0, (0.0, 4.0), [0.9, 1.2]) 
sol  = solve(prob, Tsit5(), callback = cb, tstops = [3.0])
 
plot(sol)
 
```

**Comment by ChrisRackauckas** [comment]
Hey, sorry for getting back to this one late. Your problem is a user error here. I would suggest taking a look at the examples on the callbacks and event handling page of the documentation. Specifically, you chose a DiscreteCallback that will only fire if the end of one time step is exactly 3. However, the adaptive time steps essentially have 0 chance of satisfying that so it never happens. In this case, you add a tstop=[3.0] argument to tell the solver to make sure it hits 3.0, and at that point it will fire. Remember that DiscreteCallbacks do not act continuously and are instead on the step ends themselves, so just because a condition is satisfied in the interval doesn't mean it will fire (by design).

If you wanted a callback to work on the continuous ODE solution, the version to use is Continuous callback. Here, the root finding function t-3 would fire at 3, and no tstop is required. Of course root finding is more expensive, but this will automatically find event locations (even with implicit definitions) and so it's a trade off: use the best one for your real problem.

**Comment by vnvasquez** [comment]
Thank you! This makes perfect sense.
