### ISSUE TITLE
Comparison with Mathematica is not accurate in your diagram

### ISSUE THREAD

**Issue by alihashmiii** [JuliaDiffEq/DifferentialEquations.jl#459]
Dear all,
I have been using Mathematica for quite a long time. Your comparison with Mathematica's differential equation solvers is not entirely accurate. There is built in parallelism that happens inside Mathematica's solvers. Most of the numeric code is compiled and dealt with accordingly. 

It would also be best to show which equations were compared across these multiple systems i.e. Matlab, Mathematica, Maple etc..

**Comment by ChrisRackauckas** [comment]
This isn't an actionable feature request or bug report, and pertains to a blog not directly associated with the project, so this is being closed. But feel free to continue discussion.

That blog post does need some updates again, however I need some references in order to update this:

>There is built in parallelism that happens inside Mathematica's solvers.

Can you point to the documentation on this? Of course we are excluding BLAS-based multithreading since that happens on the linear algebra involved in any package, with the same limitations anywhere (since everyone is using some form of BLAS). However, I cannot find any documentation on setting up within-method parallel, or specially-designed methods for within-steps parallelism (parallel-RKs), etc. If you can provide the sources I will add an addendum when I next get to it.

>It would also be best to show which equations were compared across these multiple systems i.e. Matlab, Mathematica, Maple etc..

Usually the standard benchmarking problems. We keep benchmarks which include the core C++/Fortran methods at https://github.com/JuliaDiffEq/DiffEqBenchmarks.jl , and of course there's more benchmarks happening (daily) as part of standard development. We always need more help keeping those updated and growing their expanse, so if you would like to see it have more depth please contribute. All of the methods in this repository have open licenses so anyone can download and run this on their own machine to see the unique performance aspects on their architecture.

MATLAB, Mathematica, and Maple present a difficult opportunity though because they have closed licenses. These licenses do not allow one to inspect the code, so all has to be learned through their own documentation and of course benchmarks. Some investigations are still online though, such as this bridge and test against MATLAB: https://github.com/JuliaDiffEq/MATLABDiffEq.jl . The other two were checked by hand back when I had a university site license (but now I do not have access). It would be great if we could keep these as part of the free benchmarking suite though. If we can find anyone who is looking to contribute Julia bridges (https://github.com/JuliaInterop/Mathematica.jl) to these languages and can provide an open license so that the benchmarks can be accessible to all who download, then we would definitely be happy to add their methods to DiffEqBenchmarks.jl.
