### ISSUE TITLE
Solver fails with in-place definition of a first order ODE

### ISSUE THREAD

**Issue by ThomasChaffey** [JuliaDiffEq/DifferentialEquations.jl#466]
Solving a first order ODE (that is, scalar state variable `u`) with an in-place definition produces the error
`MethodError: no method matching similar(::Float64)`.

A small example is solving Example 1 from the [Ordinary Differential Equations Tutorial](http://docs.juliadiffeq.org/latest/tutorials/ode_example.html) with an in-place definition:
```
using DifferentialEquations
function f(du,u,p,t)  
    du = 1.01*u
end
u0=1/2
tspan = (0.0,1.0)
prob = ODEProblem(f,u0,tspan)
sol = solve(prob)
```

No error is produced when the ODE definition is replaced with `f(u,p,t) = 1.01*u`.

I am using Julia 1.1.1 on Mac OS X 10.14.3.

**Comment by ChrisRackauckas** [comment]
```julia
function f(du,u,p,t)  
    du = 1.01*u
end
```

That is not an in-place definition. There is no such thing as in-place mutation of a number since a number is a stack-allocated bitstype. Only something that is mutable, like an array, can be mutated in-place for this to make sense. So closing since there's nothing actionable here, but feel free to ask questions.

**Comment by ChrisRackauckas** [comment]
Maybe you'll find this tutorial helpful: http://juliadiffeq.org/DiffEqTutorials.jl/html/introduction/optimizing_diffeq_code.html

**Comment by ThomasChaffey** [comment]
Thanks.  I read up on mutable/immutable objects in Julia and it makes sense that this isn't an in-place definition.
