### ISSUE TITLE
Example: Animating the solution

### ISSUE THREAD

**Issue by finmod** [JuliaDiffEq/DifferentialEquations.jl#48]
At ln[2]
using DifferentialEquations, Plots, ImageMagick
T = 5
Δx = 1//2^(3)
Δt = 1//2^(11)
fem_mesh = parabolic_squaremesh([0 1 0 1],Δx,Δt,T,:neumann)
prob = heatProblemExample_stochasticbirthdeath()

I receive the following error;

LoadError: UndefVarError: heatProblemExample_stochasticbirthdeath not defined
while loading In[3], in expression starting on line 6

**Comment by ChrisRackauckas** [comment]
The premade problems now just store the problem object directly (so that way the functions compile with the parameters in-place, was necessary to start threading tests). Now you want to do:

```julia
prob = prob_femheat_stochasticbirthdeath
```

This is defined in the premade problems here: https://github.com/JuliaDiffEq/DifferentialEquations.jl/blob/master/src/premades/premade_problems.jl#L804

I assume that you have it written like that because of previous documentation? If so, where is it written as `prob = heatProblemExample_stochasticbirthdeath()` in the docs? I'll go update that.

**Comment by finmod** [comment]
This is from the notebooks in examples. The master as well as the development folders.

 

In fact all these issues are from that folder.

 

Finmod

**Comment by ChrisRackauckas** [comment]
I found the example. Thanks!

This example was updated as suggested by the previous comment. It should no longer error.
