### ISSUE TITLE
Example: Calling External Solvers

### ISSUE THREAD

**Issue by finmod** [JuliaDiffEq/DifferentialEquations.jl#49]
In the external solvers section, 

sol =solve(prob::ODEProblem,tspan,Δt=Δt,alg=:ode45)
plot(sol,lab=["x" "y"])

LoadError: UndefVarError: ExplicitODE not defined
while loading In[4], in expression starting on line 1

 in #solve#559(::Array{Any,1}, ::Function, ::DifferentialEquations.ODEProblem{Array{Float64,1},Float64}, ::Array{Int64,1}) at C:\Users\Denis\.julia\v0.5\DifferentialEquations\src\ode\ode_solve.jl:256
 in (::DifferentialEquations.#kw##solve)(::Array{Any,1}, ::DifferentialEquations.#solve, ::DifferentialEquations.ODEProblem{Array{Float64,1},Float64}, ::Array{Int64,1}) at .\<missing>:0

then at

sol =solve(prob::ODEProblem,tspan,Δt=Δt,alg=:dopri5)
plot(sol,lab=["x" "y"])

[DifferentialEquations.jl] Initializing backend: ODEInterface
LoadError: Cannot find method(s) for dopri5! I've tried to loadODESolvers(), but it didn't work. Please check ODEInterface.help_solversupport() and call loadODESolvers and check also this output. For further information see also ODEInterface.help_install.

while loading In[5], in expression starting on line 1

 in getAllMethodPtrs(::String) at C:\Users\Denis\.julia\v0.5\ODEInterface\src\.\DLSolvers.jl:229
 in dopri5_impl(::Function, ::Float64, ::Float64, ::Array{Float64,1}, ::ODEInterface.OptionsODE, ::ODEInterface.DopriArguments{Int64}) at C:\Users\Denis\.julia\v0.5\ODEInterface\src\.\Dopri5.jl:128
 in dopri5(::Function, ::Float64, ::Float64, ::Array{Float64,1}, ::ODEInterface.OptionsODE) at C:\Users\Denis\.julia\v0.5\ODEInterface\src\.\Dopri5.jl:102
 in odecall(::ODEInterface.#dopri5, ::Function, ::Array{Float64,1}, ::Array{Float64,1}, ::ODEInterface.OptionsODE) at C:\Users\Denis\.julia\v0.5\ODEInterface\src\.\Call.jl:115
 in #solve#559(::Array{Any,1}, ::Function, ::DifferentialEquations.ODEProblem{Array{Float64,1},Float64}, ::Array{Int64,1}) at C:\Users\Denis\.julia\v0.5\DifferentialEquations\src\ode\ode_solve.jl:216
 in (::DifferentialEquations.#kw##solve)(::Array{Any,1}, ::DifferentialEquations.#solve, ::DifferentialEquations.ODEProblem{Array{Float64,1},Float64}, ::Array{Int64,1}) at .\<missing>:0

and again for the next two dopri5

Finally at

sol =solve(prob::ODEProblem,tspan,Δt=Δt,alg=:cvode_Adams)
plot(sol,lab=["x" "y"])

[DifferentialEquations.jl] Initializing backend: Sundials
LoadError: UndefVarError: cvode_fulloutput not defined
while loading In[8], in expression starting on line 1

 in #solve#559(::Array{Any,1}, ::Function, ::DifferentialEquations.ODEProblem{Array{Float64,1},Float64}, ::Array{Int64,1}) at C:\Users\Denis\.julia\v0.5\DifferentialEquations\src\ode\ode_solve.jl:317
 in (::DifferentialEquations.#kw##solve)(::Array{Any,1}, ::DifferentialEquations.#solve, ::DifferentialEquations.ODEProblem{Array{Float64,1},Float64}, ::Array{Int64,1}) at .\<missing>:0

**Comment by ChrisRackauckas** [comment]
Did you do the install from this page:?

http://juliadiffeq.github.io/DifferentialEquations.jl/latest/man/conditional_dependencies.html

Most of the installs are not for the latest tag:

- Sundials needs to be on master until the next tag.
- ODE needs to use the JuliaODE branch (@pwl's iterator PR)
- ODEInterface should work just fine on its master.

Did ODEInterface build for you? Try `Pkg.build("ODEInterface").

I realized that the links in the README broke when we moved to JuliaDiffEq, so I just pushed up a fix for that (you might need to refresh).

**Comment by finmod** [comment]
The answer is no for some of them. Should I remove the existing packages and install from  

 <http://juliadiffeq.github.io/DifferentialEquations.jl/latest/man/conditional_dependencies.html> http://juliadiffeq.github.io/DifferentialEquations.jl/latest/man/conditional_dependencies.html

What is the right sequence of commands to return to this point.

**Comment by ChrisRackauckas** [comment]
To get to the right branch for Sundials, you just need to do

```julia
Pkg.checkout("Sundials")
```

If you followed the previous instructions for using it pre-JuliaDiffEq/Sundials.jl#67, you will need to

```julia
Pkg.rm("Sundials")
Pkg.add("Sundials")
Pkg.checkout("Sundials")
Pkg.build("Sundials") #Maybe? It might build for you automatically
```

After JuliaDiffEq/Sundials.jl#75, Sundials will get a new minor tag and this will no longer be necessary.

For ODE.jl, you need to make sure you're on pwl's repo:

```julia
Pkg.rm("ODE")
Pkg.clone("https://github.com/JuliaODE/ODE.jl")
```

Notice that the command here is `clone` since `Pkg.add` will get the version from `JuliaDiffEq` which is not the work-in-progress branch that DifferentialEquations.jl is compatible with (this work-in-progress branch is set to replace the current ODE.jl sometime "soon")

ODEInterface should just work, though it might have building issues. If you run

```julia
using ODEInterface
loadODESolvers()
```

Do you get errors?

**Comment by finmod** [comment]
Sundials is now fine. Let get through the rest.

**Comment by finmod** [comment]
For ODE, it says that the package already exists.

 

This is after: Pkg.rm(“ODE”)

 

For ODEInterface, nothing doing.

**Comment by ChrisRackauckas** [comment]
You may want to use the web interface when showing code / error messages. If you tried to put them there, they didn't show up.

It might be a little messy to install pwl's branch for ODE.jl. You may need to mess with your local METADATA. Personally, when I switched back and forth I just wiped the METADATA, though that's a nuclear option which requires you re-install your packages (good for testing, bad thing to tell users). You may be able to remove the ODE folder from METADAT (METADATA/ODE), and remove the compile cache ODE.ji, and then run `Pkg.clone("https://github.com/JuliaODE/ODE.jl")`. However, note that this will make your METADATA dirty, so it may not `Pkg.update()` anymore. 

Maybe @mauro3 or @pwl knows of a better way to switch ODE between the different repos more seamlessly?

**Comment by ChrisRackauckas** [comment]
For ODEInterface, restart from the beginning. It should be:

```julia
Pkg.rm("ODEInterface")
Pkg.add("ODEInterface")
Pkg.build("ODEInterface")
loadODESolvers()
```

If nothing errors there, then it should be working.

**Comment by finmod** [comment]
At Pkg.build(“ODEInterface”), it says that currently only gfrtran is supported.

 

Does not build.

**Comment by ChrisRackauckas** [comment]
Ahh, and you said you're on Windows? You might have the same path issue I had when I first tried it: https://github.com/luchr/ODEInterface.jl/issues/2

If you are using Juno and added Julia to the path to do so, that can cause this issue.

**Comment by finmod** [comment]
So a fast resolution is to remove Juno with Pkg.rm(“Juno”) and then the series on ODEInterface again?

**Comment by ChrisRackauckas** [comment]
No. You need to explicitly give Juno the path, like:

![juno](https://cloud.githubusercontent.com/assets/1814174/18455537/65d323e8-78ff-11e6-961f-92294fbf9b11.PNG)

Then you need to make sure Julia is not in your path, install mingw-64 [from here](https://sourceforge.net/projects/mingw-w64/), and add it to your path like here:

![path](https://cloud.githubusercontent.com/assets/1814174/18455571/aa28edb6-78ff-11e6-9172-58d4e5b4297b.PNG)


Then ODEInterface should build correctly on Windows if you're using Juno (this is one of the reasons why I am making native Julia versions of all of those, because this can be a nightmare to get right!)

**Comment by mauro3** [comment]
The reason `Pkg.rm("ODE")` does not remove `ODE` is because other packages depend on it, [see](http://docs.julialang.org/en/release-0.5/manual/packages/#adding-and-removing-packages).

The way I switch is add a remote and checkout that.  I don't think this can be done from the Julia REPL.  In the shell cd to the directory of ODE.jl, (`~/.julia/v0.5/ODE` on my system):
```
git remote add JuliaODE https://github.com/JuliaODE/ODE.jl.git
git checkout JuliaODE/master
```
it will say something about a detached head, don't worry.  To go back to the original:
```
git checkout master
```
(I think)

**Comment by ChrisRackauckas** [comment]
Yeah, I feared there wasn't a pure Julia way to do it. What you're saying should work, though maybe it might need to be `git checkout origin/master`, and since `master` is used in both, if someone uses Github Desktop it will bug if you try to change between the two. So it's a little bit of a mess, but it'll fix itself when the PR is done and goes through.

**Comment by mauro3** [comment]
I guess you could open a feature request issue:
```
Pkg.checkout(pkg, [branch="master"]; merge=true, pull=true, remote=origin)
```
But probably it's fine to just leave that.  For trickier git-stuff it's easier to just git-it.

**Comment by ChrisRackauckas** [comment]
Yeah, I don't know if it's necessary since at the point where you want to specify the remote, you will have had to add the remote with Git anyways, so you probably know git (or are just following someone's instructions line by line which could just be terminal commands)

**Comment by finmod** [comment]
I am still struggling with this. Can you pls confirm the end of path for the environment variable. I cannot read your full link. Mine is:

 

C:\Program Files\mingw-w64\x86_64-6.2.0-posix-seh-rt_v5-rev1\mingw64\bin      for now.

 

Also can you indicate the content of your juliarc.jl.

 

Atome is working, Juno is installed, the Julia path has been modified as per your instructions.

 

For now, my Julia launcher on the taskbar no longer launches Julia.

 

Thanks

**Comment by ChrisRackauckas** [comment]
If you do the standard mingw install linked above and use the path

```
C:\Program Files\mingw-w64\x86_64-6.1.0-posix-seh-rt_v5-rev0\mingw64\bin
```

then `Pkg.build("ODEInterface")` should work. 

(This problem with building it is one of the reasons why I am really gunning for making Julia-native versions of its solvers right now, though its stiff solvers (Radau and when it gets LSODE) will be tough competition for some time)

**Comment by finmod** [comment]
Eureka! I can now see the light at the end of the tunnel.

 

I think that you should set up the sequence of steps to get ODEInterface running in your README file.

 

Basically, I threw everything away then:

 

Download and install the latest Julia;

Download and install Atom for Windows;

Download and install mingw-64 as indicated earlier;

 

In Atom, changed the path as you indicated earlier after installing Julia and Juno;

 

Modified the environment variables adding the mingw-64 path as indicated below;

 

Pkg.add(“”) all that is required as per your instructions. Please note that Nemo is still building cleanly. All other packages eventually build by doing Pkg.add, Pkg.checkout and Pkg.build several times if necessary.

For ODEInterface, restart from the beginning. It should be:

Pkg.rm("ODEInterface")

Pkg.add("ODEInterface")

Pkg.build("ODEInterface")

loadODESolvers()

 

Finally, Linear Work Precision Diagrams is working for all steps.

 

We can start talking about DifferentialEquations…….

**Comment by ChrisRackauckas** [comment]
Yeah, maybe I should post that somewhere (or maybe since I detailed that in this issue, that's good enough now). Technically it's not a DifferentialEquations.jl problem, but a "building ODEInterface.jl on Windows when you also have Juno installed" problem. Sundials and ODE will work out of the box once they tag new versions (/ the iterator PR JuliaDiffEq/ODE#49 goes through), but I don't know how to hide the fact that getting Fortran compilers on Windows to work correctly is a black art.

**Comment by ChrisRackauckas** [comment]
Should this issue be closed / are there any problems left here?

**Comment by finmod** [comment]
Close #49
