### ISSUE TITLE
stepping past tstop error 

### ISSUE THREAD

**Issue by Farnazmdi** [JuliaDiffEq/DifferentialEquations.jl#514]
Hey,
This this is the .jl file with the functions: [link](https://github.com/meyer-lab/DrugResponseModel.jl/blob/master/src/dde-constant.jl)
 and this one is the [notebook](https://github.com/meyer-lab/DrugResponseModel.jl/blob/master/src/DDEmodel.ipynb).

I am trying to estimate parameters for a DDE problem. I have 2 sets of data (G1 and G2) for 8 concentrations. I used to do it in a for loop, 8 concentrations separately, but here I want to do it all at once. So I have a function to solve the problem, another one to find the cost altogether, and the last one optimizing it. 
I have tried to debug by running the functions one by one, they were working correctly but the last line that is optimizing.
I really appreciate it if you could take a look at it. @ChrisRackauckas

**Comment by ChrisRackauckas** [comment]
Hey,
  Sorry this took so long. I don't know how to run your code, but https://github.com/JuliaDiffEq/DelayDiffEq.jl/pull/159 might fix your problem. Could you try running using that PR branch and see if it's okay? Otherwise, if you run the optimization, there will be a specific set of parameters on some specific DDE that is causing the issue. If you print out the parameters each time, you can isolate exactly what that is, and if you could share the DDE that is giving issues I can get it running without all of the other stuff involved and more easily hone in on what's going on.

**Comment by Farnazmdi** [comment]
Hi Chris,
Thank you for your reply. I will try running my code with the new release.

**Comment by ChrisRackauckas** [comment]
I'll merge because it's at least better than before, and then tag a release. Please give it a try when you can since there's a good chance it will have fixed the issue.

------------------------------------------------
Applied Mathematics Instructor, Massachusetts Institute of Technology
Senior Research Analyst, University of Maryland, Baltimore, School of Pharmacy, Center for Translational Medicine
On 10/22/2019 1:37:28 PM, Farnazm <notifications@github.com> wrote:
Hi Chris,
Thank you for your reply. I will try running my code with the new release.
