### ISSUE TITLE
Warning: Failed to build the parameter derivatives

### ISSUE THREAD

**Issue by yuxiliu1995** [JuliaDiffEq/DifferentialEquations.jl#541]
What does this warning mean, and how to remove it?
```julia
using DifferentialEquations, ParameterizedFunctions
ball! = @ode_def BallBounce begin
  dy =  v
  dv =  g
end g e
```
```
┌ Warning: Failed to build the parameter derivatives.
└ @ ParameterizedFunctions C:\Users\Myself\.julia\packages\ParameterizedFunctions\WcTrd\src\ode_def_opts.jl:240```

**Comment by ChrisRackauckas** [comment]
This warning means that SymEngine was unable to calculate the symbolic derivative with respect to some parameters, for god knows what reason. My guess is that it's because it thinks `e` is a special name. We've moved away from SymEngine and ParameterizedFunctions.jl for these reasons, since it seems to act wacky and non-intuitive. We recommend ModelingToolkit these days, and are scrubbing ParameterizedFunctions.jl from all of the tutorials over time. Note that this is harmless and everything still works, but it's annoying. 

Not much else to do here other than not recommend ParameterizedFunctions.jl, so closing.
