### ISSUE TITLE
Running ThreeBody Work-Precision Diagrams on Windows

### ISSUE THREAD

**Issue by finmod** [JuliaDiffEq/DifferentialEquations.jl#57]
Testing the ThreeBody notebook in Julia 0.5.0 on Windows, I get the following error:

INFO: Precompiling module DifferentialEquations.
ERROR: LoadError: LoadError: Expression needs to be of form `a, b = c`
 in include_from_node1(::String) at .\loading.jl:488 (repeats 2 times)
 in macro expansion; at .\none:2 [inlined]
 in anonymous at .\<missing>:?
 in eval(::Module, ::Any) at .\boot.jl:234
 in process_options(::Base.JLOptions) at .\client.jl:239
 in _start() at .\client.jl:318
while loading C:\Users\Denis\.julia\v0.5\DifferentialEquations\src\fem/fem_heatintegrators.jl, in expression starting on line 127
while loading C:\Users\Denis\.julia\v0.5\DifferentialEquations\src\DifferentialEquations.jl, in expression starting on line 39
Failed to precompile DifferentialEquations to C:\Users\Denis\.julia\lib\v0.5\DifferentialEquations.ji.

 in compilecache(::String) at .\loading.jl:593
 in require(::Symbol) at .\loading.jl:422

I have tried Pkg.checkou("DifferentialEquations") and Pkg.update() to no avail.

**Comment by ChrisRackauckas** [comment]
Precompile errors would show up everywhere in every test (they are at compile time, not even at runtime, so every installation would fail), but since tests are passing and clean installs are working on Windows and Linux locally for me, my only lead is that somehow something got modified or you're on an older and bad commit which `Pkg.update()` isn't fixing for some reason.

(And this is directly from the REPL, nothing in the middle?)

The file `fem_heatintegrators` isn't modified? If you modified it once, then your package would be dirty and `Pkg.update()` won't update the package. If you did, to fix it you have to pull/merge using Git, or stash the changes.

If you didn't modify it and want to go nuclear to get it back to where it should be, then delete `C:\Users\Denis.julia\lib\v0.5\DifferentialEquations.ji` and `C:\Users\Denis.julia\v0.5\DifferentialEquations\src\DifferentialEquations.jl`. The next `Pkg.update()` should give you a new installation.

**Comment by finmod** [comment]
The problem is: C:\Users\Denis.julia\lib\v0.5\DifferentialEquations.ji is not there.

 

It is not there to remove as you suggested and it is not installed after doing Pkg.rm(“DifferentialEquations”) and Pkg. add(“DifferentialEquations”) 

 

The only difference in my setup since I last ran the benchmarks is that I moved from Julia v0.5.0-rc4 to official release 0.5.0.

**Comment by ChrisRackauckas** [comment]
It should be created during `using DifferentialEquations`. Try doing that again now that you removed and re-added DifferentialEquations.

There is a precompilation issue that comes up when changing from v0.4.x to v0.5.0 that happened in the Juno stack, maybe it's what's happening here: see http://stackoverflow.com/questions/39610353/how-to-upgrade-julia-to-v0-5-0/39611666#39611666 . Maybe just delete the whole `C:\Users\Denis.julia\lib\v0.5` and let everything re-compile?

**Comment by ChrisRackauckas** [comment]
@pfitzseb had a comment which might help: 

>Pkg.rm doesn't delete packages though, they are cached in ~\.julia\v0.5\.cache, so maybe delete that and try Pkg.add again

**Comment by ChrisRackauckas** [comment]
Did any of these suggestions work?

**Comment by finmod** [comment]
In Windows, uninstalled both Julia and anaconda3. Then re-installed Julia only with IJulia and PyCall for miniconda2 internal to Julia. 

This is a lengthy process and everything is running fine on other standard packages.

 

Re-installed DifferentialEquations after Pkg.add() for NLsolve, ODEInterface and Sundials. Then Pkg.clone for ODE + checkout. 

The outcome is:

 

INFO: Precompiling module DifferentialEquations.

ERROR: LoadError: LoadError: Expression needs to be of form `a, b = c`

in include_from_node1(::String) at .\loading.jl:488 (repeats 2 times)

in macro expansion; at .\none:2 [inlined]

in anonymous at .\<missing>:?

in eval(::Module, ::Any) at .\boot.jl:234

in process_options(::Base.JLOptions) at .\client.jl:239

in _start() at .\client.jl:318

while loading C:\Users\Denis\.julia\v0.5\DifferentialEquations\src\fem/fem_heatintegrators.jl, in expression starting on line 127

while loading C:\Users\Denis\.julia\v0.5\DifferentialEquations\src\DifferentialEquations.jl, in expression starting on line 39

LoadError: Failed to precompile DifferentialEquations to C:\Users\Denis\.julia\lib\v0.5\DifferentialEquations.ji.

while loading In[17], in expression starting on line 1

 

in compilecache(::String) at .\loading.jl:593

in require(::Symbol) at .\loading.jl:422

 

Nothing doing.

**Comment by ChrisRackauckas** [comment]
I just got this error, and it showed me what it is. The dependency [Parameters.jl](https://github.com/mauro3/Parameters.jl) completely changed its syntax for the `@unpack` macro (it now says it on the README). I'll put a fix up ASAP, and I'll tag it as well.

**Comment by ChrisRackauckas** [comment]
The fix was committed as 04e71fe22ae3ed740315f5c5281e39ad7b742f9e. If you are on master, you can `Pkg.update()` and get the latest version, and it should work. Else `Pkg.checkout("DifferentialEquations")` or wait for the new release to be tagged (I'll put the PR in right now since this is breaking).

**Comment by ChrisRackauckas** [comment]
JuliaLang/METADATA.jl#6567 tagging is in progress. Thanks for altering me for this. Sorry for sending you on the wild goose hunt: for some reason my Parameters.jl took a long time to update, so I didn't run into this bug! (But I should've known about it because I was on the PR where this was discussed...)

**Comment by finmod** [comment]
Working fine now. This route of running Julia and Python via MiniConda as advocated by the READ.ME of PyCall is really good and efficient. It handles Jupyter notebook nicely. It avoids the simultaneous setup of Anaconda and miniConda on Windows and the jungle of determining/altering the home directory (C:\Users\XXX….). Thanks
