### ISSUE TITLE
event handling

### ISSUE THREAD

**Issue by zahachtah** [JuliaDiffEq/DifferentialEquations.jl#64]
just added this per our discussion yesterday

I should be able to let you define in a callback something like:

```julia 
@callback_def begin 
  # Inject code into the solver
end
```

to inject code into the solver at certain points. Then to make the event handling easier, it would have access to all of the internal variables, so I can make an event macro check for the event along the interpolation:

```julia
@event if x < 2 
  # Put the event code here
end
```

Plop that in the callback and you have event handling.

**Comment by ChrisRackauckas** [comment]
Recording my thoughts:

```julia
Θ,Δt,y₀,y₁,k₀,k₁,T::Type{Val{alg}}
```

is needed. But also `cache` (in order to `resize!` the cache) and a `user_cache` (a type which you can pass in to hold whatever data you need). Missing many parameters still, but you can see it's large. That function definition will be handled by `@callback_def` which "will do most of this". The standard callback function will include the save:

```julia
callbackfunction(Θ,Δt,y₀,y₁,k₀,k₁,T::Type{Val{alg}},...) # tons of stuff
@ode_savevalues
end
```

The reason why I include the save is because there are many reasons why you may want to include the save. For example, upon an event, add an organism. You could do that like:

```julia
@callback_def begin
  event_occurred = false
  @ode_event :exact if trait>0.5 # Exact means use NLsolve to "exact" the event time
     event_occurred = true
     t = event_time # Discard the time after the event
     u = u_event_time # Discard the time after the event
  end 10 # 10 is the amount of intermediate points to check for sign change

  @ode_savevalues # Save the values at the event time

  if event_occurred
    @ode_resizecache 1 # Add one to the length along dimension 1 (more dimensions allowed)
    u[end] = u[rand(length(u)-1)] # Make the new guys the same as one of the previous, randomly
  end
end
```

And it will essentially add the function header:

```julia
callbackfunction(Θ,Δt,y₀,y₁,k₀,k₁,T::Type{Val{alg}},...) # tons of stuff
```

which will greatly lower the user burden of remembering a crazy parameter list. 

Some explanation: `:exact` would mean that it hones in on the "exact" moment of the event, as opposed to taking the closest value which is already computed. The intermediate points is the number of points to do the initial check at. A good example is checking for x<0. You could check whether the previous timepoint and the next step are both positive, but if you have a dip in the middle you'll miss the event. So it's better to interpolate in the middle to 10 points (or some choice amount) and see if any are negative. If at least one is negative, then an event occurred, but at what time? `:quick` would just take the interpolated point  (or endpoint) which is closest and say the event happened there. `:exact` will use a root-finding algorithm to find the time in the interval where it actually occurred.

Three questions:

1. Is this easy to use?
2. Is this general enough?
3. Will it get good performance. Mainly, if you aren't using the callbacks, is your performance affected at all?

I'd like to hear input for 1 and 2 while I benchmark 3.

**Comment by zahachtah** [comment]
u where up late :-) 

1) I think it is
2) for what I am envisioning atm yes. May be a condition that can occur stochastically?

also, when the cache changes size (reduction might be needed also), at least for my problem I need to change the Arrays in the parameterised functions.

Will think more about this but its easier when you actually use it.

**Comment by ChrisRackauckas** [comment]
>also, when the cache changes size (reduction might be needed also), at least for my problem I need to change the Arrays in the parameterised functions.

I think there's a good way to handle the generically, but because the interpolation is in here, you'll have access to `f`. So you can add to it:

```julia
@callback_def begin
  event_occurred = false
  @ode_event :exact if trait>0.5 # Exact means use NLsolve to "exact" the event time
     event_occurred = true
     t = event_time # Discard the time after the event
     u = u_event_time # Discard the time after the event
  end 10 # 10 is the amount of intermediate points to check for sign change

  @ode_savevalues # Save the values at the event time

  if event_occurred
    @ode_resizecache 1 # Add one to the length along dimension 1 (more dimensions allowed)
    which_birth = rand(length(u)) # Find out which organism had a child
    u[end] = u[which_birth] # Make the new guys the same as one of the previous, randomly
    resize!(f.a,length(u)) # Resizes parameter a in f
    a[end] = u[which_birth]  # Trait inhereitance from the same organism
  end
end
```

So with what you have inside of there, you can do pretty much anything to your problem.

**Comment by ChrisRackauckas** [comment]
>May be a condition that can occur stochastically?

Yes, you can do that by taking random numbers. Stochastic events in this manner won't change convergence.

**Comment by zahachtah** [comment]
Then 1) and 2) are a go

**Comment by ChrisRackauckas** [comment]
There's no need for `user_cache` since that can be handled by making the function a call overloaded type (like a ParameterizedFunction).

**Comment by ChrisRackauckas** [comment]
I have events in callbacks working. Here's it's modeling a ball starting at a height of 50, with y1 being the height and y2 being the velocity. I made an event so when it hits the bottom it "bounces" to reflect the velocity. NLsolve is used on the interpolant to find exactly the point of contact, and so it hones in on the time of contact, making the ball never go negative. 

This callback can inject a very general amount of code, but right now takes some user know-how in order to use it. However, my current callback has an event handling function which works for (almost all) algorithms, both with adaptive timestepping and not, so it won't be hard to turn that into a macro where you could just put in a few details and it spits out event handling code.

![newplot 3](https://cloud.githubusercontent.com/assets/1814174/19404806/c5c3aba8-9225-11e6-810d-2a2056de0a5c.png)

To be able to resize the caches will take a bit of wrangling. It's "not hard", in fact it's pretty easy... I'm going to have to go to each algorithm, pack the references for the caches into a tuple, and pass that tuple to the callback. Then in the callback you could do

```julia
for x in cache
   resize!(x,length(x)+n)
end
```

to add a length `n` to each cache (grow the system by size `n`), and this will be the code that `@ode_resizecache n` generates. 

So still some work, but the heavy lifting is done.

**Comment by ChrisRackauckas** [comment]
Support has now grown from almost all to all algorithms. User facing changes next.

**Comment by zahachtah** [comment]
how would you delete arbitrary position in cache?

```julia
n=rand(1:length(x))
for x in cache
pop!(x,n)
end
```

?

**Comment by ChrisRackauckas** [comment]
```julia
n=rand(1:length(x))
for x in cache
    deleteat!(x,n)
end
```

**Comment by zahachtah** [comment]
right. is the example above available? just to see how to write it. to try it out I need to do Pkg.checkout right?

**Comment by zahachtah** [comment]
And yay! this will be very fun to play with!

**Comment by ChrisRackauckas** [comment]
The cache part isn't there yet. Everything but the cache. I hope to get that all together and the docs too tonight. I don't know how arrays of arrays will play out though: the way some of the loops work they may "work on accident" (but will have temporary allocations). I'll have to fix that up by defining new dispatches on some math operators. That's #65

**Comment by ChrisRackauckas** [comment]
Alright, the cache part is complete for some algorithms. I know `DP5` works. For some of the algorithms I might have left some variables out of `cache` in which case they will error for now. But I will be using the following to build a test to check for this, and then make sure it works for every algorithm (probably by the end of the weekend, this will be some busy-work), but I can't wait for the reveal!

Docs will be up soon. Here I am solving an equation where cells grow their concentration of `X` with `dX = aX` for a constant `a`, and when it hits `1`, they divide, giving a random amount of `X` to the new cell. 

![plot](https://cloud.githubusercontent.com/assets/1814174/19410993/923d6840-92ad-11e6-86bb-f78d28884ef7.png)

![plot2](https://cloud.githubusercontent.com/assets/1814174/19410992/923caf4a-92ad-11e6-9a5a-0ece6c54810f.png)

**Comment by ChrisRackauckas** [comment]
`@ode_change_deleteat` has been implemented and it should work with all ODE algorithms. I'll make something similar for SDEs soon, but there's a cool mathematical problem that I think will result in a paper (for how to do the interpolation). We'll  see how this goes. As always, please star the repo if you find this useful (it's how I'm showing my boss that it's being used!) and open another issue if you have a feature-request of bug report.

**Comment by zahachtah** [comment]
starred, and amazing work Chris, thanks
